#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_ROOT="$PROJECT_ROOT/build/sm64-modern-engine-runtime-smoke"
mkdir -p "$BUILD_ROOT"

xcrun swiftc \
  -parse-as-library \
  -swift-version 6 \
  -Xfrontend -strict-concurrency=complete \
  -module-cache-path "$BUILD_ROOT/module-cache" \
  "$PROJECT_ROOT/SM64Modern/EngineAuthority.swift" \
  "$PROJECT_ROOT/SM64Modern/ObjectPool.swift" \
  "$PROJECT_ROOT/SM64Modern/MemoryArena.swift" \
  "$PROJECT_ROOT/SM64Modern/EngineState.swift" \
  "$PROJECT_ROOT/SM64Modern/DeterministicPrimitives.swift" \
  "$PROJECT_ROOT/SM64Modern/GeneratedTrigTables.swift" \
  "$PROJECT_ROOT/SM64Modern/ObjectTransform.swift" \
  "$PROJECT_ROOT/SM64Modern/ObjectScheduler.swift" \
  "$PROJECT_ROOT/SM64Modern/ProgressionState.swift" \
  "$PROJECT_ROOT/SM64Modern/ProgressionActors.swift" \
  "$PROJECT_ROOT/SM64Modern/SaveFileCodec.swift" \
  "$PROJECT_ROOT/SM64Modern/CoinScoreAges.swift" \
  "$PROJECT_ROOT/SM64Modern/SaveFileMutator.swift" \
  "$PROJECT_ROOT/SM64Modern/ProgressionPersistence.swift" \
  "$PROJECT_ROOT/SM64Modern/ProgressionRuntime.swift" \
  "$PROJECT_ROOT/SM64Modern/InputCore.swift" \
  "$PROJECT_ROOT/SM64Modern/MarioInputCore.swift" \
  "$PROJECT_ROOT/SM64Modern/SurfacePartition.swift" \
  "$PROJECT_ROOT/SM64Modern/SurfaceCollision.swift" \
  "$PROJECT_ROOT/SM64Modern/MarioGeometryInput.swift" \
  "$PROJECT_ROOT/SM64Modern/MarioState.swift" \
  "$PROJECT_ROOT/SM64Modern/MarioAction.swift" \
  "$PROJECT_ROOT/SM64Modern/MarioActionCancels.swift" \
  "$PROJECT_ROOT/SM64Modern/OracleTrace.swift" \
  "$PROJECT_ROOT/SM64Modern/ChainChompRelease.swift" \
  "$PROJECT_ROOT/SM64Modern/ChainChompReleaseObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/OwnerThreadEffectRouter.swift" \
  "$PROJECT_ROOT/SM64Modern/Respawner.swift" \
  "$PROJECT_ROOT/SM64Modern/RespawnerObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/DecorativePendulumBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/DecorativePendulumObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/MadPianoBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/MadPianoObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/ActSelectorBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/ActSelectorObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/NpcMenuBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/NpcMenuObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/PushableMetalBoxBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/PushableMetalBoxObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SquarishPathMovingBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SquarishPathMovingObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SushiSharkBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SushiSharkObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TiltingBowserLavaPlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TiltingBowserLavaPlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BehaviorDispatchBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/ArrowLiftBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/ArrowLiftObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/ElevatorBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/ElevatorObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SeesawPlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SeesawPlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SwingPlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SwingPlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/RotatingPlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/RotatingPlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TTCMovingBarBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TTCMovingBarObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TTCSpinnerBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TTCSpinnerObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TTCTreadmillBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TTCTreadmillObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TTCPendulumBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TTCPendulumObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TTCElevatorBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TTCElevatorObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TTCRotatingSolidBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TTCRotatingSolidObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TTC2DRotatorBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TTC2DRotatorObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TTCCogBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TTCCogObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/PyramidElevatorBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/PyramidElevatorObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/PyramidTopFragmentBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/PyramidTopFragmentObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/PyramidPillarTouchDetectorBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/PyramidPillarTouchDetectorObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/PyramidTopBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/PyramidTopObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TTCPitBlockBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TTCPitBlockObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/StaticCheckeredPlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/StaticCheckeredPlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BBHTiltingTrapPlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BBHTiltingTrapPlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/LLLSinkingPlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/LLLSinkingPlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WfRotatingWoodenPlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WfRotatingWoodenPlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/RotatingOctagonalPlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/RotatingOctagonalPlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WfSolidTowerPlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WfSolidTowerPlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WfTowerPlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WfTowerPlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TrackBallBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TrackBallObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WfSlidingPlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WfSlidingPlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WdwExpressElevatorBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WdwExpressElevatorObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/LllSinkingRockBlockBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/LllSinkingRockBlockObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SslMovingPyramidWallBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SslMovingPyramidWallObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/ThiIslandTopBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/ThiIslandTopObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/VolcanoFallingTrapBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/VolcanoFallingTrapObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/RollingLogBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/RollingLogObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/LllMovingOctagonalMeshBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/LllMovingOctagonalMeshObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/FerrisWheelPlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/FerrisWheelPlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/CheckerboardPlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/CheckerboardPlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WfTowerPlatformGroupBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WfTowerPlatformGroupObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/LllRotatingHexagonalPlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/LllRotatingHexagonalPlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/LllRotatingHexFlameBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/LllRotatingHexFlameObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/LllRotatingFireBarBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/LllRotatingFireBarObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/ActivatedBackAndForthPlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/ActivatedBackAndForthPlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BitfsSinkingPlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BitfsSinkingPlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/DddMovingPoleBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/DddMovingPoleObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/LllRotatingHexagonalRingBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/LllRotatingHexagonalRingObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/LllWoodPieceBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/LllFloatingWoodBridgeBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/LllFloatingWoodBridgeObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SquishablePlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SquishablePlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/LllDrawbridgeBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/LllDrawbridgeObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/IdleWaterWaveBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/IdleWaterWaveObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterfallSoundLoopBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterfallSoundLoopObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/VolcanoSoundLoopBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/VolcanoSoundLoopObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TumblingBridgeBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TumblingBridgeObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/FloatingPlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/FloatingPlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/JrbFloatingBoxBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/JrbFloatingBoxObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SlidingPlatform2Behavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SlidingPlatform2ObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SmallWaterWaveBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SmallWaterWaveObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/AmbientSoundLoopBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/AmbientSoundLoopObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/RotatingExclamationMarkBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/RotatingExclamationMarkObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterAirBubbleBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterAirBubbleObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/ObjectBubbleBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/ObjectBubbleObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterDropletBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterDropletObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterMistBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterMistObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterMist2Behavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterMist2ObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterSplashBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterSplashObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BubbleMaybeBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BubbleMaybeObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WindBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WindObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/JetStreamBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/JetStreamObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/JetStreamWaterRingBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/JetStreamWaterRingObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/JetStreamRingSpawnerBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/JetStreamRingSpawnerObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/MantaRayWaterRingBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/MantaRayWaterRingObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WhirlpoolBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WhirlpoolObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/MantaRayBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/MantaRayObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/ShallowWaterWaveBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/ShallowWaterWaveObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterSplashSpawnerBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterSplashSpawnerObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BubbleParticleSpawnerBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BubbleParticleSpawnerObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/PiranhaPlantWakingBubbleBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/PiranhaPlantWakingBubbleObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/PiranhaPlantBubbleBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/PiranhaPlantBubbleObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WaveTrailBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WaveTrailObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/StrongWindParticleBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/StrongWindParticleObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterParticleBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterParticleObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/PlungeBubbleBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/PlungeBubbleObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BreathParticleSpawnerBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BreathParticleSpawnerObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/MistParticleBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/MistParticleObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/MistParticleSpawnerBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/MistParticleSpawnerObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TweesterSandParticleBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TweesterSandParticleObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/FlameMarioBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/FlameMarioObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BlackSmokeBowserBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BlackSmokeBowserObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BlackSmokeUpwardBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BlackSmokeUpwardObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WhitePuffSmokeBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WhitePuffSmokeObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WhitePuffSmoke2Behavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WhitePuffSmoke2ObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WhitePuffExplosionBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WhitePuffExplosionObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/DustSmokeBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/DustSmokeObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/StarKeyCollectionPuffSpawnerBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/StarKeyCollectionPuffSpawnerObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/FlameBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/FlameObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/FlamethrowerFlameBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/FlamethrowerFlameObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/FlameBouncingBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/FlameBouncingObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BowserFlameBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BowserFlameObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BlueFlamesGroupBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BlueFlamesGroupObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/FlameFloatingLandingBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/FlameFloatingLandingObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BlueBowserFlameBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BlueBowserFlameObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/VolcanoFlamesBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/VolcanoFlamesObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/KoopaShellFlameBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/KoopaShellFlameObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/FlameMovingForwardGrowingBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/FlameMovingForwardGrowingObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BetaMovingFlamesBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BetaMovingFlamesObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BowserFlameSpawnBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BowserFlameSpawnObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SmallPiranhaFlameBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SmallPiranhaFlameObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/FireSpitterBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/FireSpitterObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/FirePiranhaPlantBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/FirePiranhaPlantObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/FlamethrowerBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/FlamethrowerObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/CelebrationStarSparkleBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/CelebrationStarSparkleObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/GroundParticleSpawnerBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/GroundParticleSpawnerObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/AnimatedTextureBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/AnimatedTextureObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SparkleBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SparkleObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SparkleSpawnerBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SparkleSpawnerObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/AmbientSoundsBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/AmbientSoundsObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/CoinSparklesBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/CoinSparklesObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/GoldenCoinSparklesBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/GoldenCoinSparklesObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/PurpleParticleBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/PurpleParticleObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TinyStarParticleBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TinyStarParticleObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TinyStarParticleSpawnerBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TinyStarParticleSpawnerObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TriangleParticleBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TriangleParticleObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TriangleParticleSpawnerBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TriangleParticleSpawnerObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TreeLeafBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TreeLeafObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TreeParticleSpawnerBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TreeParticleSpawnerObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/MistCircParticleSpawnerBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/MistCircParticleSpawnerObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SparkleParticleSpawnerBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SparkleParticleSpawnerObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SimpleAnimationBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SimpleAnimationObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/UnusedFakeStarBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/UnusedFakeStarObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/CloudPartBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/CloudPartObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BreakBoxTriangleBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BreakBoxTriangleObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/CannonBaseUnusedBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/CannonBaseUnusedObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/NoOpBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/NoOpObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/CannonBarrelBubblesBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/CannonBarrelBubblesObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/CloudBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/CloudObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/CelebrationStarBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/CelebrationStarObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WarpBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WarpObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/DddWarpBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/DddWarpObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/ActSelectorStarTypeBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/ActSelectorStarTypeObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/CollectStarBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/CollectStarObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/StarSpawnCoordinatesBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/StarSpawnCoordinatesObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SpawnedStarBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SpawnedStarObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/CcmTouchedStarSpawnBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/CcmTouchedStarSpawnObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/HiddenStarBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/HiddenStarObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/CastleCannonGrateBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/CastleCannonGrateObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BlueCoinBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BlueCoinObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/RedCoinBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/RedCoinObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/StarDoorBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/StarDoorObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/CapSwitchBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/CapSwitchObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/MetalCapBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/MetalCapObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/VanishCapBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/VanishCapObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WingCapBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WingCapObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/NormalCapBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/NormalCapObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TowerDoorBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TowerDoorObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/OpenableGrillBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/OpenableGrillObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/DoorBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/DoorObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/HiddenObjectBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/HiddenObjectObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/RecoveryHeartBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/RecoveryHeartObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/CoinBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/CoinFormationBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/CoinInsideBooBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BlueFishBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BlueFishObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/ClamShellBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/ClamShellObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BobombAnchorMarioBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BobombAnchorMarioObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BubBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BubObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BubbaBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BubbaObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BowlingBallBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BowlingBallObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/DDDPoleBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/DDDPoleObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/DonutPlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/DonutPlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/CourtyardBooTripletBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/CourtyardBooTripletObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/FallingBowserPlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/FallingBowserPlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/GiantPoleBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/GiantPoleObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/KoopaFlagBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/KoopaFlagObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/KoopaRaceEndpointBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/KoopaRaceEndpointObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WfBreakableWallBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WfBreakableWallObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/UnusedPoundablePlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/UnusedPoundablePlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/YellowBackgroundMenuBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/YellowBackgroundMenuObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SnowMoundBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SnowMoundObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/RrCruiserWingBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/RrCruiserWingObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SpindriftBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SpindriftObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SpindelBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SpindelObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/RrRotatingBridgePlatformBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/RrRotatingBridgePlatformObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SnowmanWindBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SnowmanWindObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/MrBlizzardSnowballBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/MrBlizzardSnowballObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/UnlockDoorStarBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/UnlockDoorStarObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/EndCutsceneActorBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/EndCutsceneActorObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/EndBirdsBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/EndBirdsObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BeginningPeachBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BeginningPeachObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/ButterflyBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/ButterflyObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TiltingPyramidBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TiltingPyramidObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BookendBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BookendObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BookSwitchBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BookSwitchObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/HauntedBookshelfBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/HauntedBookshelfObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/HauntedBookshelfManagerBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/HauntedBookshelfManagerObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/HauntedChairBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/HauntedChairObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/FishBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/FishObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/CannonBarrelBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/CannonBarrelObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/CannonBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/CannonObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/MerryGoRoundBooManagerBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/MerryGoRoundBooManagerObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/CoinObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/MovingCoinBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/MovingCoinObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterLevelBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterLevelObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterPillarBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterPillarObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/FloorSwitchBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/FloorSwitchObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/AnimatedFloorSwitchBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/AnimatedFloorSwitchObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/HiddenOneUpBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/HiddenOneUpObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BreakableBoxBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BreakableBoxObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/JumpingBoxBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/JumpingBoxObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/KickableBoardBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/KickableBoardObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/ExclamationBoxBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/ExclamationBoxObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/OrangeNumberBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/OrangeNumberObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SoundSpawnerBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SoundSpawnerObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/RockSolidBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/RockSolidObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/ToxBoxBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/ToxBoxObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/EnvironmentGateBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/EnvironmentGateObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/ClockArmBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/ClockArmObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/CastleFloorTrapBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/CastleFloorTrapObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/CastleFlagBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/CastleFlagObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BooCageBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BooCageObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BooKeyBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BooKeyObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BooInCastleBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BooInCastleObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/MerryGoRoundBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/MerryGoRoundObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/MusicTouchBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/MusicTouchObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TextSurfaceBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TextSurfaceObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/GrandStarBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/GrandStarObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BetaBowserAnchorBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BetaBowserAnchorObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/AmpEnemy.swift" \
  "$PROJECT_ROOT/SM64Modern/AmpObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BooEnemy.swift" \
  "$PROJECT_ROOT/SM64Modern/BooObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BobombEnemy.swift" \
  "$PROJECT_ROOT/SM64Modern/BobombObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BirdEnemy.swift" \
  "$PROJECT_ROOT/SM64Modern/BirdObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SwoopEnemy.swift" \
  "$PROJECT_ROOT/SM64Modern/SwoopObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/PiranhaPlant.swift" \
  "$PROJECT_ROOT/SM64Modern/PiranhaPlantObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/PokeyEnemy.swift" \
  "$PROJECT_ROOT/SM64Modern/PokeyObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/ScuttlebugEnemy.swift" \
  "$PROJECT_ROOT/SM64Modern/ScuttlebugObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BobombBuddyBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BobombBuddyObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BowserShockWave.swift" \
  "$PROJECT_ROOT/SM64Modern/BowserShockWaveObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BowserKey.swift" \
  "$PROJECT_ROOT/SM64Modern/BowserKeyObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BouncingFireball.swift" \
  "$PROJECT_ROOT/SM64Modern/BouncingFireballObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/KingBobombBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/KingBobombCollision.swift" \
  "$PROJECT_ROOT/SM64Modern/KingBobombHomeMovement.swift" \
  "$PROJECT_ROOT/SM64Modern/KingBobombObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SLWalkingPenguinBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SLWalkingPenguinCollision.swift" \
  "$PROJECT_ROOT/SM64Modern/SLWalkingPenguinMovement.swift" \
  "$PROJECT_ROOT/SM64Modern/SLWalkingPenguinObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SmallPenguinBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SmallPenguinMovement.swift" \
  "$PROJECT_ROOT/SM64Modern/SmallPenguinObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/KoopaShell.swift" \
  "$PROJECT_ROOT/SM64Modern/KoopaShellObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BowserKeyCutscene.swift" \
  "$PROJECT_ROOT/SM64Modern/BowserKeyCutsceneObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/Explosion.swift" \
  "$PROJECT_ROOT/SM64Modern/ExplosionChildren.swift" \
  "$PROJECT_ROOT/SM64Modern/ExplosionObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/MoneybagEnemy.swift" \
  "$PROJECT_ROOT/SM64Modern/MoneybagObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterBomb.swift" \
  "$PROJECT_ROOT/SM64Modern/WaterBombObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/EyerokBoss.swift" \
  "$PROJECT_ROOT/SM64Modern/EyerokHand.swift" \
  "$PROJECT_ROOT/SM64Modern/EyerokHandCollision.swift" \
  "$PROJECT_ROOT/SM64Modern/EyerokObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/MrIEnemy.swift" \
  "$PROJECT_ROOT/SM64Modern/MrIObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/RacingPenguinBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/RacingPenguinPath.swift" \
  "$PROJECT_ROOT/SM64Modern/RacingPenguinRaceChildren.swift" \
  "$PROJECT_ROOT/SM64Modern/RacingPenguinObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/YoshiBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/YoshiObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BowserBomb.swift" \
  "$PROJECT_ROOT/SM64Modern/BowserBombObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/TuxiesMotherBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/TuxiesMotherEyes.swift" \
  "$PROJECT_ROOT/SM64Modern/TuxiesMotherObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BigBooEnemy.swift" \
  "$PROJECT_ROOT/SM64Modern/BigBooCollision.swift" \
  "$PROJECT_ROOT/SM64Modern/BigBooObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/FlyGuyEnemy.swift" \
  "$PROJECT_ROOT/SM64Modern/FlyGuyObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BulletBill.swift" \
  "$PROJECT_ROOT/SM64Modern/BulletBillObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/GoombaEnemy.swift" \
  "$PROJECT_ROOT/SM64Modern/GoombaObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SpinyEnemy.swift" \
  "$PROJECT_ROOT/SM64Modern/SpinyObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/EnemyLakitu.swift" \
  "$PROJECT_ROOT/SM64Modern/EnemyLakituObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/ChainChompEnemy.swift" \
  "$PROJECT_ROOT/SM64Modern/ChainChompObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SnufitEnemy.swift" \
  "$PROJECT_ROOT/SM64Modern/SnufitObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/WhompCollision.swift" \
  "$PROJECT_ROOT/SM64Modern/WhompEnemy.swift" \
  "$PROJECT_ROOT/SM64Modern/WhompObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BompBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BompObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/ThwompBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/ThwompObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BoulderBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BoulderObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BoulderGeneratorBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/HorizontalGrindelBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/HorizontalGrindelObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/UnusedParticleSpawnObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/UnusedParticleSpawnBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SnowmanCheckpointBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SnowmanCheckpointObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SnowmanHeadBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SnowmanHeadObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BowserBodyAnchorBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BowserBodyAnchorObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BowserTailAnchorBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BowserTailAnchorObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BetaChestBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BetaChestObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BetaTrampolineBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BetaTrampolineObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BetaHoldableBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/BetaHoldableObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SeaweedBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SeaweedObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/ShipPart3Behavior.swift" \
  "$PROJECT_ROOT/SM64Modern/ShipPart3ObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SunkenShipPartBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/SunkenShipPartObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/JrbSlidingBoxBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/JrbSlidingBoxObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/FallingPillarBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/FallingPillarObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/CoffinBehavior.swift" \
  "$PROJECT_ROOT/SM64Modern/CoffinObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/HeaveHoEnemy.swift" \
  "$PROJECT_ROOT/SM64Modern/HeaveHoObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/ChuckyaEnemy.swift" \
  "$PROJECT_ROOT/SM64Modern/ChuckyaObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/SkeeterEnemy.swift" \
  "$PROJECT_ROOT/SM64Modern/SkeeterObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/BullyCollision.swift" \
  "$PROJECT_ROOT/SM64Modern/BullyEnemy.swift" \
  "$PROJECT_ROOT/SM64Modern/BullyObjectBridge.swift" \
  "$PROJECT_ROOT/SM64Modern/EngineAuthorityLedger.swift" \
  "$PROJECT_ROOT/SM64Modern/EngineRuntime.swift" \
  "$PROJECT_ROOT/tests/sm64_modern_engine_runtime_smoke.swift" \
  -o "$BUILD_ROOT/sm64-modern-engine-runtime-smoke"

"$BUILD_ROOT/sm64-modern-engine-runtime-smoke"
