import Foundation

private struct ManifestRow: Comparable, Hashable {
    let identity: String
    let source: String
    let mapping: String
    let owner: String
    let reason: String

    var encoded: String {
        [identity, source, mapping, owner, reason].joined(separator: "|")
    }

    static func < (lhs: ManifestRow, rhs: ManifestRow) -> Bool {
        Array(lhs.encoded.utf8).lexicographicallyPrecedes(Array(rhs.encoded.utf8))
    }
}

private enum ManifestError: Error, CustomStringConvertible {
    case invalidArguments(String)
    case invalidReachabilityRow(String)
    case duplicateRow(String)
    case outputFailed(String)

    var description: String {
        switch self {
        case let .invalidArguments(message), let .invalidReachabilityRow(message),
             let .duplicateRow(message), let .outputFailed(message):
            return message
        }
    }
}

@main
struct SM64BehaviorCoverageManifestTool {
    private struct Options {
        let reachability: String
        let output: String
    }

    private static let swiftRoutes: [String: (owner: String, reason: String)] = [
        "bhvAmp": ("AmpObjectBridge", "value kernel plus generation-safe owner bridge"),
        "bhvUkiki": ("UkikiObjectBridge", "Ukiki value kernel plus generation-safe owner bridge"),
        "bhvMacroUkiki": ("UkikiObjectBridge", "shared Macro Ukiki identity on the Ukiki owner route"),
        "bhvUkikiCage": ("UkikiCageObjectBridge", "Ukiki cage value/owner route"),
        "bhvUkikiCageStar": ("UkikiCageObjectBridge", "Ukiki cage star child/effect route"),
        "bhvMips": ("MipsObjectBridge", "MIPS value kernel plus generation-safe owner bridge"),
        "bhvToadMessage": ("ToadMessageObjectBridge", "Toad message value/owner route"),
        "bhvMenuButton": ("MenuButtonObjectBridge", "file-select menu button value/owner route"),
        "bhvMenuButtonManager": ("MenuButtonObjectBridge", "file-select menu manager owner route"),
        "bhvPushableMetalBox": ("PushableMetalBoxObjectBridge", "pushable metal box value/owner route"),
        "bhvTiltingBowserLavaPlatform": ("TiltingBowserLavaPlatformObjectBridge", "Bowser 2 tilting lava platform value/owner route"),
        "bhvMadPiano": ("MadPianoObjectBridge", "Mad Piano value kernel plus generation-safe owner bridge"),
        "bhvActSelector": ("ActSelectorObjectBridge", "act-selector parent/child value/owner route"),
        "bhvArrowLift": ("ArrowLiftObjectBridge", "arrow-lift value kernel plus owner route"),
        "bhvHmcElevatorPlatform": ("ElevatorObjectBridge", "shared HMC elevator value/owner route"),
        "bhvMeshElevator": ("ElevatorObjectBridge", "shared mesh elevator value/owner route"),
        "bhvRrElevatorPlatform": ("ElevatorObjectBridge", "shared RR elevator value/owner route"),
        "bhvSeesawPlatform": ("SeesawPlatformObjectBridge", "seesaw platform value/owner route"),
        "bhvSwingPlatform": ("SwingPlatformObjectBridge", "swing platform value/owner route"),
        "bhvRotatingPlatform": ("RotatingPlatformObjectBridge", "rotating platform value/owner route"),
        "bhvTTCMovingBar": ("TTCMovingBarObjectBridge", "TTC moving-bar value/owner route"),
        "bhvTTCSpinner": ("TTCSpinnerObjectBridge", "TTC spinner value/owner route"),
        "bhvTTCTreadmill": ("TTCTreadmillObjectBridge", "TTC treadmill value/owner route"),
        "bhvTTCPendulum": ("TTCPendulumObjectBridge", "TTC pendulum value/owner route"),
        "bhvTTCElevator": ("TTCElevatorObjectBridge", "TTC elevator value/owner route"),
        "bhvTTCRotatingSolid": ("TTCRotatingSolidObjectBridge", "TTC rotating-solid value/owner route"),
        "bhvTTC2DRotator": ("TTC2DRotatorObjectBridge", "TTC 2D rotator value/owner route"),
        "bhvTTCCog": ("TTCCogObjectBridge", "TTC cog value/owner route"),
        "bhvPyramidElevator": ("PyramidElevatorObjectBridge", "pyramid elevator value/owner route"),
        "bhvPyramidElevatorTrajectoryMarkerBall": ("PyramidElevatorObjectBridge", "pyramid elevator marker child route"),
        "bhvPyramidTopFragment": ("PyramidTopFragmentObjectBridge", "pyramid top fragment spin/retirement route"),
        "bhvPyramidPillarTouchDetector": ("PyramidPillarTouchDetectorObjectBridge", "pyramid pillar collision/deactivation route"),
        "bhvPyramidTop": ("PyramidTopObjectBridge", "pyramid top solve/spin/explode route"),
        "bhvTTCPitBlock": ("TTCPitBlockObjectBridge", "TTC pit-block value/owner route"),
        "bhvSquarishPathMoving": ("SquarishPathMovingObjectBridge", "BitDW squarish path-moving platform value/owner route"),
        "bhvStaticCheckeredPlatform": ("StaticCheckeredPlatformObjectBridge", "static checkered platform value/owner route"),
        "bhvBbhTiltingTrapPlatform": ("BBHTiltingTrapPlatformObjectBridge", "BBH tilting-trap platform value/owner route"),
        "bhvLllSinkingRectangularPlatform": ("LLLSinkingPlatformObjectBridge", "LLL rectangular sinking platform value/owner route"),
        "bhvLllSinkingSquarePlatforms": ("LLLSinkingPlatformObjectBridge", "LLL square sinking platform value/owner route"),
        "bhvWfRotatingWoodenPlatform": ("WfRotatingWoodenPlatformObjectBridge", "WF rotating wooden platform value/owner route"),
        "bhvOctagonalPlatformRotating": ("RotatingOctagonalPlatformObjectBridge", "rotating octagonal platform value/owner route"),
        "bhvWfSolidTowerPlatform": ("WfSolidTowerPlatformObjectBridge", "WF solid tower platform child route"),
        "bhvWfElevatorTowerPlatform": ("WfTowerPlatformObjectBridge", "WF elevator tower platform child route"),
        "bhvWfSlidingTowerPlatform": ("WfTowerPlatformObjectBridge", "WF sliding tower platform child route"),
        "bhvWfSlidingPlatform": ("WfSlidingPlatformObjectBridge", "WF sliding brick platform value/owner route"),
        "bhvTrackBall": ("TrackBallObjectBridge", "platform-on-track child lifetime route"),
        "bhvWdwExpressElevator": ("WdwExpressElevatorObjectBridge", "WDW express elevator value/owner route"),
        "bhvWdwExpressElevatorPlatform": ("WdwExpressElevatorObjectBridge", "WDW express static platform no-op route"),
        "bhvLllSinkingRockBlock": ("LllSinkingRockBlockObjectBridge", "LLL sinking rock block value/owner route"),
        "bhvSslMovingPyramidWall": ("SslMovingPyramidWallObjectBridge", "SSL moving pyramid-wall oscillator route"),
        "bhvThiHugeIslandTop": ("ThiIslandTopObjectBridge", "THI huge-island water-drain route"),
        "bhvThiTinyIslandTop": ("ThiIslandTopObjectBridge", "THI tiny-island pound/drain route"),
        "bhvLllVolcanoFallingTrap": ("VolcanoFallingTrapObjectBridge", "LLL volcano falling-trap action route"),
        "bhvTtmRollingLog": ("RollingLogObjectBridge", "TTM rolling-log motion/boundary route"),
        "bhvLllRollingLog": ("RollingLogObjectBridge", "LLL rolling-log motion/boundary route"),
        "bhvLllMovingOctagonalMeshPlatform": ("LllMovingOctagonalMeshObjectBridge", "LLL moving octagonal mesh value/owner route"),
        "bhvFerrisWheelAxle": ("FerrisWheelPlatformObjectBridge", "Ferris wheel axle owner route"),
        "bhvFerrisWheelPlatform": ("FerrisWheelPlatformObjectBridge", "Ferris wheel platform child route"),
        "bhvCheckerboardElevatorGroup": ("CheckerboardPlatformObjectBridge", "checkerboard elevator group owner route"),
        "bhvCheckerboardPlatformSub": ("CheckerboardPlatformObjectBridge", "checkerboard platform child route"),
        "bhvTowerPlatformGroup": ("WfTowerPlatformGroupObjectBridge", "WF tower platform group spawner route"),
        "bhvLllRotatingHexagonalPlatform": ("LllRotatingHexagonalPlatformObjectBridge", "LLL rotating hexagonal platform value/owner route"),
        "bhvLllRotatingHexFlame": ("LllRotatingHexFlameObjectBridge", "LLL rotating hex flame child route"),
        "bhvLllRotatingBlockWithFireBars": ("LllRotatingFireBarObjectBridge", "LLL rotating fire-bar parent route"),
        "bhvActivatedBackAndForthPlatform": ("ActivatedBackAndForthPlatformObjectBridge", "activated back-and-forth platform value/owner route"),
        "bhvBitfsSinkingPlatforms": ("BitfsSinkingPlatformObjectBridge", "BITFS sinking platform value/owner route"),
        "bhvBitfsSinkingCagePlatform": ("BitfsSinkingPlatformObjectBridge", "BITFS sinking cage value/owner route"),
        "bhvDddMovingPole": ("DddMovingPoleObjectBridge", "DDD moving pole parent-copy child route"),
        "bhvLllRotatingHexagonalRing": ("LllRotatingHexagonalRingObjectBridge", "LLL rotating hexagonal ring parent route"),
        "bhvLllFloatingWoodBridge": ("LllFloatingWoodBridgeObjectBridge", "LLL floating wood bridge parent route"),
        "bhvLllWoodPiece": ("LllWoodPieceObjectBridge", "LLL floating wood piece child route"),
        "bhvSquishablePlatform": ("SquishablePlatformObjectBridge", "squishable platform value/owner route"),
        "bhvLllDrawbridgeSpawner": ("LllDrawbridgeObjectBridge", "LLL drawbridge spawner parent route"),
        "bhvLllDrawbridge": ("LllDrawbridgeObjectBridge", "LLL drawbridge surface child route"),
        "bhvIdleWaterWave": ("IdleWaterWaveObjectBridge", "idle water wave value/owner route"),
        "bhvObjectWaterWave": ("IdleWaterWaveObjectBridge", "shared object water wave value/owner route"),
        "bhvWaterfallSoundLoop": ("WaterfallSoundLoopObjectBridge", "waterfall sound loop value/owner route"),
        "bhvVolcanoSoundLoop": ("VolcanoSoundLoopObjectBridge", "volcano sound loop value/owner route"),
        "bhvBigBoo": ("BigBooObjectBridge", "variant value kernel plus owner/effect route"),
        "bhvBigBully": ("BullyObjectBridge", "Bully value/movement/reward owner route"),
        "bhvBigBullyWithMinions": ("BullyObjectBridge", "Bully minion-parent owner route"),
        "bhvBigChillBully": ("BullyObjectBridge", "Chief Chilly big-bully owner route"),
        "bhvBalconyBigBoo": ("BigBooObjectBridge", "balcony Big Boo variant owner route"),
        "bhvBird": ("BirdObjectBridge", "bird value and owner route"),
        "bhvBouncingFireball": ("BouncingFireballObjectBridge", "bouncing fireball owner route"),
        "bhvBouncingFireballFlame": ("BouncingFireballObjectBridge", "bouncing fireball flame child route"),
        "bhvBobomb": ("BobombObjectBridge", "Bob-omb value/owner route"),
        "bhvBobombBuddy": ("BobombBuddyObjectBridge", "dialog/cannon owner route"),
        "bhvBobombBuddyOpensCannon": ("BobombBuddyObjectBridge", "cannon-role Bob-omb Buddy owner route"),
        "bhvBobombBullyDeathSmoke": ("ExplosionObjectBridge", "shared ground-smoke child route"),
        "bhvBobombExplosionBubble": ("ExplosionObjectBridge", "shared water-bubble child route"),
        "bhvBobombExplosionBubble3600": ("ExplosionObjectBridge", "embedded bubble3600 deterministic jitter route"),
        "bhvBoo": ("BooObjectBridge", "Boo value/owner route"),
        "bhvBooBossSpawnedBridge": ("BigBooObjectBridge", "Big Boo staircase bridge child route"),
        "bhvBowserBomb": ("BowserBombObjectBridge", "Bowser bomb owner route"),
        "bhvBowserBombExplosion": ("BowserBombObjectBridge", "Bowser mine-flame route"),
        "bhvBowserBombSmoke": ("BowserBombObjectBridge", "Bowser mine-smoke route"),
        "bhvBowserKey": ("BowserKeyObjectBridge", "Bowser key owner route"),
        "bhvBowserKeyCourseExit": ("BowserKeyCutsceneObjectBridge", "course-exit key cutscene route"),
        "bhvBowserKeyUnlockDoor": ("BowserKeyCutsceneObjectBridge", "unlock-door key cutscene route"),
        "bhvBowserShockWave": ("BowserShockwaveObjectBridge", "Bowser shockwave owner route"),
        "bhvBulletBill": ("BulletBillObjectBridge", "Bullet Bill value/owner route"),
        "bhvChainChomp": ("ChainChompObjectBridge", "chain chomp value/owner route"),
        "bhvChainChompChainPart": ("ChainChompObjectBridge", "chain chomp segment child route"),
        "bhvChainChompGate": ("ChainChompReleaseObjectBridge", "chain chomp gate owner route"),
        "bhvChuckya": ("ChuckyaObjectBridge", "Chuckya value/owner route"),
        "bhvChuckyaAnchorMario": ("ChuckyaObjectBridge", "Chuckya anchored-Mario child route"),
        "bhvCannonClosed": ("BobombBuddyObjectBridge", "Bob-omb Buddy cannon-closed child route"),
        "bhvEyerok": ("EyerokObjectBridge", "Eyerok boss owner route"),
        "bhvEyerokBoss": ("EyerokObjectBridge", "Eyerok boss owner route"),
        "bhvEyerokHand": ("EyerokObjectBridge", "Eyerok hand owner route"),
        "bhvEnemyLakitu": ("EnemyLakituObjectBridge", "enemy Lakitu owner route"),
        "bhvExplosion": ("ExplosionObjectBridge", "shared generic explosion route"),
        "bhvFlyGuy": ("FlyGuyObjectBridge", "Fly Guy value/owner route"),
        "bhvFlyguyFlame": ("FlyGuyObjectBridge", "Fly Guy flame child route"),
        "bhvGoomba": ("GoombaObjectBridge", "Goomba value/owner route"),
        "bhvGoombaTripletSpawner": ("GoombaObjectBridge", "Goomba triplet spawner owner route"),
        "bhvHeaveHo": ("HeaveHoObjectBridge", "Heave Ho value/owner route"),
        "bhvHeaveHoThrowMario": ("HeaveHoObjectBridge", "Heave Ho throw-Mario child owner route"),
        "bhvGhostHuntBigBoo": ("BigBooObjectBridge", "Ghost Hunt Big Boo variant owner route"),
        "bhvHomingAmp": ("AmpObjectBridge", "homing Amp variant owner route"),
        "bhvKingBobomb": ("KingBobombObjectBridge", "King Bob-omb value/owner route"),
        "bhvKingWhomp": ("WhompObjectBridge", "King Whomp value/owner route"),
        "bhvKoopaShell": ("KoopaShellObjectBridge", "Koopa shell value/owner route"),
        "bhvKoopaShellUnderwater": ("KoopaShellObjectBridge", "underwater Koopa shell owner route"),
        "bhvLakitu": ("LakituObjectBridge", "Lakitu value/owner route"),
        "bhvLllTumblingBridge": ("TumblingBridgeObjectBridge", "LLL tumbling bridge parent route"),
        "bhvWfTumblingBridge": ("TumblingBridgeObjectBridge", "WF tumbling bridge parent route"),
        "bhvBbhTumblingBridge": ("TumblingBridgeObjectBridge", "BBH tumbling bridge parent route"),
        "bhvTumblingBridgePlatform": ("TumblingBridgeObjectBridge", "tumbling bridge platform child route"),
        "bhvWdwSquareFloatingPlatform": ("FloatingPlatformObjectBridge", "WDW square floating platform shared route"),
        "bhvWdwRectangularFloatingPlatform": ("FloatingPlatformObjectBridge", "WDW rectangular floating platform shared route"),
        "bhvJrbFloatingPlatform": ("FloatingPlatformObjectBridge", "JRB floating platform shared route"),
        "bhvJrbFloatingBox": ("JrbFloatingBoxObjectBridge", "JRB floating box sine-height route"),
        "bhvJrbSlidingBox": ("JrbSlidingBoxObjectBridge", "JRB parent-relative sliding box route"),
        "bhvSlidingPlatform2": ("SlidingPlatform2ObjectBridge", "packed sliding platform value/owner route"),
        "bhvSmallWaterWave": ("SmallWaterWaveObjectBridge", "small water wave value/owner route"),
        "bhvBirdsSoundLoop": ("AmbientSoundLoopObjectBridge", "birds ambient sound loop shared route"),
        "bhvSandSoundLoop": ("AmbientSoundLoopObjectBridge", "moving-sand ambient sound loop shared route"),
        "bhvRotatingExclamationMark": ("RotatingExclamationMarkObjectBridge", "exclamation mark parent-lifetime route"),
        "bhvWaterAirBubble": ("WaterAirBubbleObjectBridge", "water-air bubble value/owner route"),
        "bhvObjectBubble": ("ObjectBubbleObjectBridge", "object bubble water-boundary route"),
        "bhvWaterDroplet": ("WaterDropletObjectBridge", "water droplet gravity/splash route"),
        "bhvWaterMist": ("WaterMistObjectBridge", "water mist opacity/lifetime route"),
        "bhvWaterMist2": ("WaterMist2ObjectBridge", "water mist cloud home-level route"),
        "bhvBubbleSplash": ("WaterSplashObjectBridge", "air-bubble surface splash owner route"),
        "bhvWaterDropletSplash": ("WaterSplashObjectBridge", "water-droplet surface splash owner route"),
        "bhvObjectWaterSplash": ("WaterSplashObjectBridge", "object-created water splash child route"),
        "bhvBubbleParticleSpawner": ("BubbleParticleSpawnerObjectBridge", "bubble particle child spawner route"),
        "bhvPiranhaPlantWakingBubbles": ("PiranhaPlantWakingBubbleObjectBridge", "Piranha Plant waking bubble physics route"),
        "bhvPiranhaPlantBubble": ("PiranhaPlantBubbleObjectBridge", "Piranha Plant parent bubble action route"),
        "bhvWaveTrail": ("WaveTrailObjectBridge", "Mario water wave trail route"),
        "bhvObjectWaveTrail": ("WaveTrailObjectBridge", "object-created water wave trail route"),
        "bhvSushiShark": ("SushiSharkObjectBridge", "Sushi shark movement/collision/effect route"),
        "bhvSushiSharkCollisionChild": ("SushiSharkObjectBridge", "Sushi shark invisible collision child route"),
        "bhvStrongWindParticle": ("StrongWindParticleObjectBridge", "strong wind hazard particle route"),
        "bhvTinyStrongWindParticle": ("StrongWindParticleObjectBridge", "tiny strong wind visual particle route"),
        "bhvSmallParticle": ("WaterParticleObjectBridge", "small water particle route"),
        "bhvSmallParticleSnow": ("WaterParticleObjectBridge", "small snow water particle route"),
        "bhvSmallParticleBubbles": ("WaterParticleObjectBridge", "small bubble water particle route"),
        "bhvPlungeBubble": ("PlungeBubbleObjectBridge", "plunge bubble particle spawner route"),
        "bhvBreathParticleSpawner": ("BreathParticleSpawnerObjectBridge", "breath water-mist spawner route"),
        "bhvWhitePuff1": ("MistParticleObjectBridge", "white puff one mist child route"),
        "bhvWhitePuff2": ("MistParticleObjectBridge", "white puff two mist child route"),
        "bhvMistParticleSpawner": ("MistParticleSpawnerObjectBridge", "mist particle child spawner route"),
        "bhvTweesterSandParticle": ("TweesterSandParticleObjectBridge", "Tweester sand particle movement route"),
        "bhvBlackSmokeMario": ("BlackSmokeMarioObjectBridge", "Mario black-smoke child route"),
        "bhvFireParticleSpawner": ("FlameMarioObjectBridge", "Mario flame particle route"),
        "bhvBlackSmokeBowser": ("BlackSmokeBowserObjectBridge", "Bowser black-smoke child route"),
        "bhvBlackSmokeUpward": ("BlackSmokeUpwardObjectBridge", "upward black-smoke parent route"),
        "bhvWhitePuffSmoke": ("WhitePuffSmokeObjectBridge", "white puff smoke route"),
        "bhvWhitePuffSmoke2": ("WhitePuffSmoke2ObjectBridge", "moving white puff smoke route"),
        "bhvWhitePuffExplosion": ("WhitePuffExplosionObjectBridge", "white puff explosion route"),
        "bhvSmoke": ("DustSmokeObjectBridge", "dust smoke route"),
        "bhvBobombFuseSmoke": ("DustSmokeObjectBridge", "Bob-omb fuse dust smoke route"),
        "bhvStarKeyCollectionPuffSpawner": ("StarKeyCollectionPuffSpawnerObjectBridge", "star-key collection puff spawner route"),
        "bhvFlame": ("FlameObjectBridge", "static flame interaction route"),
        "bhvFlamethrowerFlame": ("FlamethrowerFlameObjectBridge", "flamethrower flame route"),
        "bhvFlameBouncing": ("FlameBouncingObjectBridge", "bouncing flame route"),
        "bhvFlameBowser": ("BowserFlameObjectBridge", "Bowser flame route"),
        "bhvFlameLargeBurningOut": ("BowserFlameObjectBridge", "large burning-out Bowser flame route"),
        "bhvBlueFlamesGroup": ("BlueFlamesGroupObjectBridge", "blue-flame group parent route"),
        "bhvFlameFloatingLanding": ("FlameFloatingLandingObjectBridge", "floating landing flame route"),
        "bhvBlueBowserFlame": ("BlueBowserFlameObjectBridge", "blue Bowser flame route"),
        "bhvVolcanoFlames": ("VolcanoFlamesObjectBridge", "volcano flame route"),
        "bhvKoopaShellFlame": ("KoopaShellFlameObjectBridge", "Koopa-shell flame route"),
        "bhvFlameMovingForwardGrowing": ("FlameMovingForwardGrowingObjectBridge", "moving/growing flame route"),
        "bhvBetaMovingFlamesSpawn": ("BetaMovingFlamesObjectBridge", "Beta moving-flame spawner route"),
        "bhvBetaMovingFlames": ("BetaMovingFlamesObjectBridge", "Beta moving-flame child route"),
        "bhvBowserFlameSpawn": ("BowserFlameSpawnObjectBridge", "Bowser flame trajectory spawner route"),
        "bhvSmallPiranhaFlame": ("SmallPiranhaFlameObjectBridge", "small Piranha flame route"),
        "bhvFireSpitter": ("FireSpitterObjectBridge", "fire-spitter route"),
        "bhvFirePiranhaPlant": ("FirePiranhaPlantObjectBridge", "fire Piranha Plant route"),
        "bhvFlamethrower": ("FlamethrowerObjectBridge", "flamethrower parent route"),
        "bhvCelebrationStarSparkle": ("CelebrationStarSparkleObjectBridge", "celebration star sparkle route"),
        "bhvCelebrationStar": ("CelebrationStarObjectBridge", "celebration star parent orbit/face-camera route"),
        "bhvWarp": ("WarpObjectBridge", "normal warp hitbox/reset route"),
        "bhvFadingWarp": ("WarpObjectBridge", "fading warp hitbox/reset route"),
        "bhvWarpPipe": ("WarpObjectBridge", "warp-pipe hitbox/reset/collision route"),
        "bhvExitPodiumWarp": ("WarpObjectBridge", "exit-podium warp hitbox/collision route"),
        "bhvDddWarp": ("DddWarpObjectBridge", "DDD warp global collision-selection route"),
        "bhvActSelectorStarType": ("ActSelectorStarTypeObjectBridge", "act-selector star pulse/rotation route"),
        "bhvStar": ("CollectStarObjectBridge", "collectible star rotation/interaction route"),
        "bhvStarSpawnCoordinates": ("StarSpawnCoordinatesObjectBridge", "star spawn trajectory/time-stop route"),
        "bhvSpawnedStar": ("SpawnedStarObjectBridge", "spawned star trajectory/cutscene route"),
        "bhvSpawnedStarNoLevelExit": ("SpawnedStarObjectBridge", "no-level-exit spawned star trajectory route"),
        "bhvCcmTouchedStarSpawn": ("CcmTouchedStarSpawnObjectBridge", "CCM slide-triggered star spawn route"),
        "bhvHiddenStar": ("HiddenStarObjectBridge", "hidden-star trigger/reveal parent route"),
        "bhvHiddenStarTrigger": ("HiddenStarObjectBridge", "hidden-star collision trigger route"),
        "bhvBowserCourseRedCoinStar": ("HiddenStarObjectBridge", "Bowser course red-coin hidden-star reveal route"),
        "bhvHiddenAt120Stars": ("CastleCannonGrateObjectBridge", "120-star cannon grate gate route"),
        "bhvBlueCoinSwitch": ("BlueCoinObjectBridge", "blue-coin switch recede/tick route"),
        "bhvHiddenBlueCoin": ("BlueCoinObjectBridge", "hidden blue-coin switch/interaction route"),
        "bhvHiddenRedCoinStar": ("RedCoinObjectBridge", "hidden red-coin star gate/reveal route"),
        "bhvRedCoinStarMarker": ("RedCoinObjectBridge", "red-coin star marker rotation route"),
        "bhvRedCoin": ("RedCoinObjectBridge", "red-coin counter/interaction route"),
        "bhvStarDoor": ("StarDoorObjectBridge", "paired star-door open/close route"),
        "bhvCapSwitch": ("CapSwitchObjectBridge", "cap-switch activation/press route"),
        "bhvCapSwitchBase": ("CapSwitchObjectBridge", "cap-switch base collision route"),
        "bhvMetalCap": ("MetalCapObjectBridge", "metal-cap physics/tangibility route"),
        "bhvVanishCap": ("VanishCapObjectBridge", "vanish-cap physics/opacity route"),
        "bhvWingCap": ("WingCapObjectBridge", "wing-cap physics/opacity route"),
        "bhvNormalCap": ("NormalCapObjectBridge", "normal-cap physics/save route"),
        "bhvTowerDoor": ("TowerDoorObjectBridge", "tower-door attack/explosion route"),
        "bhvOpenableGrill": ("OpenableGrillObjectBridge", "openable grill parent route"),
        "bhvOpenableCageDoor": ("OpenableGrillObjectBridge", "openable grill cage-door child route"),
        "bhvDoor": ("DoorObjectBridge", "normal door action/sound route"),
        "bhvDoorWarp": ("DoorObjectBridge", "warp door action/sound route"),
        "bhvHiddenObject": ("HiddenObjectObjectBridge", "switch-gated hidden object route"),
        "bhvRecoveryHeart": ("RecoveryHeartObjectBridge", "recovery-heart spin/heal route"),
        "bhvOneCoin": ("CoinObjectBridge", "one-coin yellow coin route"),
        "bhvYellowCoin": ("CoinObjectBridge", "yellow coin interaction route"),
        "bhvTemporaryYellowCoin": ("CoinObjectBridge", "temporary yellow coin blink route"),
        "bhvMovingYellowCoin": ("MovingCoinObjectBridge", "moving yellow coin route"),
        "bhvMovingBlueCoin": ("MovingCoinObjectBridge", "moving blue coin route"),
        "bhvBlueCoinSliding": ("MovingCoinObjectBridge", "unused blue coin sliding action route"),
        "bhvBlueCoinJumping": ("MovingCoinObjectBridge", "unused blue coin jumping action route"),
        "bhvWaterLevelDiamond": ("WaterLevelObjectBridge", "water-level diamond route"),
        "bhvInitializeChangingWaterLevel": ("WaterLevelObjectBridge", "changing water-level initializer route"),
        "bhvWaterLevelPillar": ("WaterPillarObjectBridge", "water-level pillar/moat-drain route"),
        "bhvFloorSwitchHardcodedModel": ("FloorSwitchObjectBridge", "hardcoded purple floor-switch route"),
        "bhvFloorSwitchGrills": ("FloorSwitchObjectBridge", "grill purple floor-switch route"),
        "bhvFloorSwitchAnimatesObject": ("FloorSwitchObjectBridge", "animated purple floor-switch route"),
        "bhvFloorSwitchHiddenObjects": ("FloorSwitchObjectBridge", "hidden-object purple floor-switch route"),
        "bhvPurpleSwitchHiddenBoxes": ("FloorSwitchObjectBridge", "GOTO-alias purple hidden-box switch route"),
        "bhvAnimatesOnFloorSwitchPress": ("AnimatedFloorSwitchObjectBridge", "animated floor-switch child route"),
        "bhvHidden1up": ("HiddenOneUpObjectBridge", "hidden one-up reveal route"),
        "bhvHidden1upTrigger": ("HiddenOneUpObjectBridge", "hidden one-up trigger route"),
        "bhvHidden1upInPole": ("HiddenOneUpObjectBridge", "pole hidden one-up route"),
        "bhvHidden1upInPoleTrigger": ("HiddenOneUpObjectBridge", "pole hidden one-up trigger route"),
        "bhvHidden1upInPoleSpawner": ("HiddenOneUpObjectBridge", "pole hidden one-up spawner route"),
        "bhv1Up": ("HiddenOneUpObjectBridge", "stationary one-up interaction route"),
        "bhv1upWalking": ("HiddenOneUpObjectBridge", "walking one-up route"),
        "bhv1upRunningAway": ("HiddenOneUpObjectBridge", "running-away one-up route"),
        "bhv1upSliding": ("HiddenOneUpObjectBridge", "sliding one-up route"),
        "bhv1upJumpOnApproach": ("HiddenOneUpObjectBridge", "jump-on-approach one-up route"),
        "bhvBreakableBoxSmall": ("BreakableBoxObjectBridge", "small holdable breakable box route"),
        "bhvBreakableBox": ("BreakableBoxObjectBridge", "large breakable box route"),
        "bhvJumpingBox": ("JumpingBoxObjectBridge", "jumping box held/free/thrown route"),
        "bhvKickableBoard": ("KickableBoardObjectBridge", "kickable board rock/fall route"),
        "bhvKoopaFlag": ("KoopaFlagObjectBridge", "Koopa race flag pole-base route"),
        "bhvPoleGrabbing": ("KoopaFlagObjectBridge", "shared pole-base grabbing route"),
        "bhvTree": ("KoopaFlagObjectBridge", "shared pole-base tree route"),
        "bhvKoopaRaceEndpoint": ("KoopaRaceEndpointObjectBridge", "Koopa race finish endpoint route"),
        "bhvWfBreakableWallLeft": ("WfBreakableWallObjectBridge", "WF breakable wall left cannon-shot route"),
        "bhvWfBreakableWallRight": ("WfBreakableWallObjectBridge", "WF breakable wall right cannon-shot route"),
        "bhvUnusedPoundablePlatform": ("UnusedPoundablePlatformObjectBridge", "unused poundable platform ground-pound route"),
        "bhvYellowBackgroundInMenu": ("YellowBackgroundMenuObjectBridge", "yellow menu background scale/rotation route"),
        "bhvSlidingSnowMound": ("SnowMoundObjectBridge", "sliding snow mound action route"),
        "bhvSnowMoundSpawn": ("SnowMoundObjectBridge", "snow mound timed spawner route"),
        "bhvRrCruiserWing": ("RrCruiserWingObjectBridge", "RR cruiser wing oscillation route"),
        "bhvSpindrift": ("SpindriftObjectBridge", "Spindrift enemy action/movement route"),
        "bhvSpindel": ("SpindelObjectBridge", "Spindel phase/rotation route"),
        "bhvRrRotatingBridgePlatform": ("RrRotatingBridgePlatformObjectBridge", "RR rotating bridge/flamethrower route"),
        "bhvSLSnowmanWind": ("SnowmanWindObjectBridge", "Snowman wind/dialog route"),
        "bhvMrBlizzardSnowball": ("MrBlizzardSnowballObjectBridge", "Mr Blizzard snowball projectile route"),
        "bhvUnlockDoorStar": ("UnlockDoorStarObjectBridge", "unlock-door star rise/particle lifetime route"),
        "bhvExclamationBox": ("ExclamationBoxObjectBridge", "exclamation box content route"),
        "bhvOrangeNumber": ("OrangeNumberObjectBridge", "orange number counter route"),
        "bhvSoundSpawner": ("SoundSpawnerObjectBridge", "one-shot sound spawner route"),
        "bhvRockSolid": ("RockSolidObjectBridge", "rock-solid collision route"),
        "bhvToxBox": ("ToxBoxObjectBridge", "Tox Box direction-table collision route"),
        "bhvBowserSubDoor": ("EnvironmentGateObjectBridge", "Bowser submarine door unlock route"),
        "bhvBowsersSub": ("EnvironmentGateObjectBridge", "Bowser submarine unlock route"),
        "bhvMoatGrills": ("EnvironmentGateObjectBridge", "moat-grill drain collision route"),
        "bhvInvisibleObjectsUnderBridge": ("EnvironmentGateObjectBridge", "under-bridge moat environment initializer"),
        "bhvClockHourHand": ("ClockArmObjectBridge", "TTC hour-hand speed arm route"),
        "bhvClockMinuteHand": ("ClockArmObjectBridge", "TTC minute-hand speed selector route"),
        "bhvCastleFloorTrap": ("CastleFloorTrapObjectBridge", "castle floor-trap parent route"),
        "bhvFloorTrapInCastle": ("CastleFloorTrapObjectBridge", "castle floor-trap child route"),
        "bhvCastleFlagWaving": ("CastleFlagObjectBridge", "castle flag animation initializer route"),
        "bhvBooCage": ("BooCageObjectBridge", "Boo cage parent-linked entrance route"),
        "bhvAlphaBooKey": ("BooKeyObjectBridge", "alpha Boo-key rotation/collection route"),
        "bhvBetaBooKey": ("BooKeyObjectBridge", "beta Boo-key parent/drop route"),
        "bhvBooInCastle": ("BooInCastleObjectBridge", "castle Boo room/opacity route"),
        "bhvMerryGoRound": ("MerryGoRoundObjectBridge", "merry-go-round rotation/wind route"),
        "bhvPlaysMusicTrackWhenTouched": ("MusicTouchObjectBridge", "distance-gated puzzle-jingle route"),
        "bhvMessagePanel": ("TextSurfaceObjectBridge", "message-panel text surface route"),
        "bhvSignOnWall": ("TextSurfaceObjectBridge", "wall-sign text surface route"),
        "bhvCutOutObject": ("NoOpObjectBridge", "render-disabled break-only no-op route"),
        "bhvRotatingCounterClockwise": ("NoOpObjectBridge", "break-only terminal no-op route"),
        "bhvStub": ("NoOpObjectBridge", "render-disabled break-only stub route"),
        "bhvStub1D0C": ("NoOpObjectBridge", "deactivate-only terminal stub route"),
        "bhvStub1D70": ("NoOpObjectBridge", "break-only terminal stub route"),
        "unused_1": ("NoOpObjectBridge", "literal-break terminal helper route"),
        "bhvStaticObject": ("NoOpObjectBridge", "static render setup then break route"),
        "bhvYellowBall": ("NoOpObjectBridge", "billboard setup then break route"),
        "bhvCarrySomething1": ("NoOpObjectBridge", "break-only carry helper route"),
        "bhvCarrySomething2": ("NoOpObjectBridge", "break-only carry helper route"),
        "bhvCarrySomething3": ("NoOpObjectBridge", "break-only carry helper route"),
        "bhvCarrySomething4": ("NoOpObjectBridge", "break-only carry helper route"),
        "bhvCarrySomething5": ("NoOpObjectBridge", "break-only carry helper route"),
        "bhvCarrySomething6": ("NoOpObjectBridge", "break-only carry helper route"),
        "bhvSmallWaterWave398": ("SmallWaterWaveObjectBridge", "source-verified small-wave helper subroutine"),
        "bhvIgloo": ("NoOpObjectBridge", "static igloo barrier field/reset route"),
        "bhvBigSnowmanWhole": ("NoOpObjectBridge", "static text-interaction snowman field/reset route"),
        "bhvUkikiCageChild": ("NoOpObjectBridge", "fixed-position terminal cage-child route"),
        "bhvSunkenShipPart2": ("NoOpObjectBridge", "static rotated terminal ship-part route"),
        "bhvSunkenShipPart": ("SunkenShipPartObjectBridge", "sunken-ship distance opacity route"),
        "bhvSunkenShipSetRotation": ("NoOpObjectBridge", "source-verified ship-part rotation helper"),
        "bhvTower": ("NoOpObjectBridge", "static tower collision-load route"),
        "bhvBulletBillCannon": ("NoOpObjectBridge", "static Bullet Bill cannon collision-load route"),
        "bhvLllHexagonalMesh": ("NoOpObjectBridge", "static LLL hex-mesh collision-load route"),
        "bhvHiddenStaircaseStep": ("NoOpObjectBridge", "room-scoped staircase collision-load route"),
        "bhvPillarBase": ("NoOpObjectBridge", "static pillar-base collision-load route"),
        "bhvInSunkenShip": ("NoOpObjectBridge", "source-verified sunken-ship collision alias"),
        "bhvInSunkenShip2": ("NoOpObjectBridge", "rotated sunken-ship collision-load route"),
        "bhvMantaRayRingManager": ("NoOpObjectBridge", "empty persistent manager loop route"),
        "bhvBetaFishSplashSpawner": ("NoOpObjectBridge", "non-functional water-level sample route"),
        "bhvSmallBomp": ("BompObjectBridge", "small Bomp action/movement owner route"),
        "bhvLargeBomp": ("BompObjectBridge", "large Bomp action/movement owner route"),
        "bhvGrindel": ("ThwompObjectBridge", "Grindel shared thwomp action owner route"),
        "bhvThwomp2": ("ThwompObjectBridge", "Thwomp2 shared thwomp action owner route"),
        "bhvThwomp": ("ThwompObjectBridge", "Thwomp shared thwomp action owner route"),
        "bhvBigBoulder": ("BoulderObjectBridge", "big boulder rolling owner route"),
        "bhvBigBoulderGenerator": ("BoulderObjectBridge", "big boulder radius/timer generator route"),
        "bhvHorizontalGrindel": ("HorizontalGrindelObjectBridge", "horizontal Grindel movement/collision route"),
        "bhvUnusedParticleSpawn": ("UnusedParticleSpawnObjectBridge", "collision-triggered purple-particle spawner route"),
        "bhvSnowmansBodyCheckpoint": ("SnowmanCheckpointObjectBridge", "parent-linked snowman checkpoint route"),
        "bhvSnowmansHead": ("SnowmanHeadObjectBridge", "snowman head dialog/fall/reward route"),
        "bhvBowserBodyAnchor": ("BowserBodyAnchorObjectBridge", "parent-transform Bowser body hitbox route"),
        "bhvBowserTailAnchor": ("BowserTailAnchorObjectBridge", "parent-linked Bowser tail tangible route"),
        "bhvBetaChestBottom": ("BetaChestObjectBridge", "beta chest bottom/lid owner route"),
        "bhvBetaChestLid": ("BetaChestObjectBridge", "beta chest lid owner route"),
        "bhvBetaTrampolineTop": ("BetaTrampolineObjectBridge", "beta trampoline top owner route"),
        "bhvBetaTrampolineSpring": ("BetaTrampolineObjectBridge", "beta trampoline spring owner route"),
        "bhvBetaHoldableObject": ("BetaHoldableObjectBridge", "beta holdable state/physics owner route"),
        "bhvSeaweed": ("SeaweedObjectBridge", "fixed seaweed descriptor child route"),
        "bhvSeaweedBundle": ("SeaweedObjectBridge", "four-child seaweed bundle route"),
        "bhvShipPart3": ("ShipPart3ObjectBridge", "oscillating decorative ship-part route"),
        "bhvInSunkenShip3": ("ShipPart3ObjectBridge", "oscillating ship-part collision route"),
        "bhvFallingPillar": ("FallingPillarObjectBridge", "distance-triggered falling pillar route"),
        "bhvFallingPillarHitbox": ("FallingPillarObjectBridge", "parent-tracking falling pillar hitbox route"),
        "bhvCoffinSpawner": ("CoffinObjectBridge", "BBH six-coffin room spawner route"),
        "bhvCoffin": ("CoffinObjectBridge", "coffin stand-up/collision route"),
        "bhvThreeCoinsSpawn": ("CoinObjectBridge", "three-coin formation spawner route"),
        "bhvTenCoinsSpawn": ("CoinObjectBridge", "ten-coin formation spawner route"),
        "bhvSingleCoinGetsSpawned": ("CoinObjectBridge", "formation child coin route"),
        "bhvCoinFormation": ("CoinObjectBridge", "patterned coin formation spawner route"),
        "bhvCoinFormationSpawn": ("CoinObjectBridge", "patterned coin formation child route"),
        "bhvCoinInsideBoo": ("CoinObjectBridge", "parent-following Boo coin release route"),
        "bhvBlueFish": ("BlueFishObjectBridge", "aquarium blue-fish dive/turn route"),
        "bhvTankFishGroup": ("BlueFishObjectBridge", "room-gated fifteen-fish group route"),
        "bhvClamShell": ("ClamShellObjectBridge", "clam open/close bubble burst route"),
        "bhvBobombAnchorMario": ("BobombAnchorMarioObjectBridge", "parent-relative Mario anchor route"),
        "bhvBub": ("BubObjectBridge", "water Bub movement/retirement route"),
        "bhvChirpChirp": ("BubObjectBridge", "Bub spawner alias route"),
        "bhvChirpChirpUnused": ("BubObjectBridge", "Bub spawner implementation route"),
        "bhvBubba": ("BubbaObjectBridge", "underwater Bubba patrol/chomp movement route"),
        "bhvBobBowlingBallSpawner": ("BowlingBallObjectBridge", "Bob-omb Battlefield bowling-ball spawner route"),
        "bhvTtmBowlingBallSpawner": ("BowlingBallObjectBridge", "TTM bowling-ball spawner route"),
        "bhvThiBowlingBallSpawner": ("BowlingBallObjectBridge", "THI bowling-ball spawner route"),
        "bhvPitBowlingBall": ("BowlingBallObjectBridge", "pit bowling-ball physics route"),
        "bhvBowlingBall": ("BowlingBallObjectBridge", "path-following bowling-ball roll route"),
        "bhvFreeBowlingBall": ("BowlingBallObjectBridge", "free bowling-ball idle/roll/reset route"),
        "bhvDDDPole": ("DDDPoleObjectBridge", "DDD pole save-gated oscillating route"),
        "bhvDonutPlatformSpawner": ("DonutPlatformObjectBridge", "Donut Platform 31-child distance spawner route"),
        "bhvDonutPlatform": ("DonutPlatformObjectBridge", "Donut Platform gravity/destruction child route"),
        "bhvCourtyardBooTriplet": ("CourtyardBooTripletObjectBridge", "12-star courtyard Boo triplet spawner route"),
        "bhvFallingBowserPlatform": ("FallingBowserPlatformObjectBridge", "Bowser-triggered falling platform action route"),
        "bhvGiantPole": ("GiantPoleObjectBridge", "Giant Pole top-ball spawn and pole route"),
        "bhvEndPeach": ("EndCutsceneActorObjectBridge", "ending Peach animation progression route"),
        "bhvEndToad": ("EndCutsceneActorObjectBridge", "ending Toad animation progression route"),
        "bhvEndBirds1": ("EndBirdsObjectBridge", "ending cutscene near-target bird route"),
        "bhvEndBirds2": ("EndBirdsObjectBridge", "ending cutscene camera-target bird route"),
        "bhvBeginningPeach": ("BeginningPeachObjectBridge", "intro Peach camera/opacity action route"),
        "bhvButterfly": ("ButterflyObjectBridge", "rest/follow/return butterfly route"),
        "bhvBooWithCage": ("BooObjectBridge", "cage Boo shared chase/death route"),
        "bhvGhostHuntBoo": ("BooObjectBridge", "shared Ghost Hunt Boo script route"),
        "bhvMerryGoRoundBoo": ("BooObjectBridge", "Merry-Go-Round Boo shared script route"),
        "bhvBitfsTiltingInvertedPyramid": ("TiltingPyramidObjectBridge", "BITFS tilting normal/collision route"),
        "bhvAnotherTiltingPlatform": ("TiltingPyramidObjectBridge", "shared tilting platform normal route"),
        "bhvLllTiltingInvertedPyramid": ("TiltingPyramidObjectBridge", "LLL tilting normal/collision route"),
        "bhvBookendSpawn": ("BookendObjectBridge", "haunted bookend proximity spawner route"),
        "bhvFlyingBookend": ("BookendObjectBridge", "flying bookend launch route"),
        "bhvBookSwitch": ("BookSwitchObjectBridge", "haunted bookshelf switch route"),
        "bhvHauntedBookshelf": ("HauntedBookshelfObjectBridge", "haunted bookshelf recede/collision route"),
        "bhvHauntedBookshelfManager": ("HauntedBookshelfManagerObjectBridge", "haunted bookshelf switch/sequence manager route"),
        "bhvHauntedChair": ("HauntedChairObjectBridge", "haunted chair lift/launch route"),
        "bhvFish": ("FishObjectBridge", "generic fish child movement route"),
        "bhvFish2": ("FishObjectBridge", "blue twenty-fish group route"),
        "bhvFish3": ("FishObjectBridge", "blue five-fish group route"),
        "bhvFishGroup": ("FishObjectBridge", "generic fish group route"),
        "bhvLargeFishGroup": ("FishObjectBridge", "large fish group route"),
        "bhvCannonBarrel": ("CannonBarrelObjectBridge", "parent-copy cannon barrel route"),
        "bhvCannon": ("CannonObjectBridge", "opened cannon action/interaction route"),
        "bhvMerryGoRoundBooManager": ("MerryGoRoundBooManagerObjectBridge", "merry-go-round Boo spawn/goal manager route"),
        "bhvGrandStar": ("GrandStarObjectBridge", "grand-star cutscene/interaction route"),
        "bhvBetaBowserAnchor": ("BetaBowserAnchorObjectBridge", "Mario-relative Beta Bowser anchor route"),
        "bhvAnotherElavator": ("ElevatorObjectBridge", "shared elevator init/loop route"),
        "bhvDirtParticleSpawner": ("GroundParticleSpawnerObjectBridge", "ground sand particle spawner route"),
        "bhvSnowParticleSpawner": ("GroundParticleSpawnerObjectBridge", "ground snow particle spawner route"),
        "bhvAnimatedTexture": ("AnimatedTextureObjectBridge", "animated texture home-position and cadence route"),
        "bhvSparkle": ("SparkleObjectBridge", "sparkle animation/deactivation route"),
        "bhvSparkleSpawn": ("SparkleSpawnerObjectBridge", "sparkle child spawner route"),
        "bhvAmbientSounds": ("AmbientSoundsObjectBridge", "camera-gated ambient sound init route"),
        "bhvCoinSparkles": ("CoinSparklesObjectBridge", "coin sparkle animation/deactivation route"),
        "bhvGoldenCoinSparkles": ("GoldenCoinSparklesObjectBridge", "golden coin sparkle child spawner route"),
        "bhvPurpleParticle": ("PurpleParticleObjectBridge", "purple particle random velocity route"),
        "bhvWallTinyStarParticle": ("TinyStarParticleObjectBridge", "wall tiny-star particle route"),
        "bhvPoundTinyStarParticle": ("TinyStarParticleObjectBridge", "pound tiny-star particle route"),
        "bhvVertStarParticleSpawner": ("TinyStarParticleSpawnerObjectBridge", "vertical tiny-star particle spawner route"),
        "bhvHorStarParticleSpawner": ("TinyStarParticleSpawnerObjectBridge", "horizontal tiny-star particle spawner route"),
        "bhvPunchTinyTriangle": ("TriangleParticleObjectBridge", "punch tiny-triangle particle route"),
        "bhvTriangleParticleSpawner": ("TriangleParticleSpawnerObjectBridge", "triangle particle spawner route"),
        "bhvTreeLeaf": ("TreeLeafObjectBridge", "tree leaf phase/gravity particle route"),
        "bhvTreeSnow": ("TreeLeafObjectBridge", "tree snow phase/gravity particle route"),
        "bhvLeafParticleSpawner": ("TreeParticleSpawnerObjectBridge", "level-gated tree particle spawner route"),
        "bhvMistCircParticleSpawner": ("MistCircParticleSpawnerObjectBridge", "mist-circle white-puff spawner route"),
        "bhvSparkleParticleSpawner": ("SparkleParticleSpawnerObjectBridge", "sparkle particle animation spawner route"),
        "bhvRandomAnimatedTexture": ("SimpleAnimationObjectBridge", "random animated texture script route"),
        "bhvUnused0DFC": ("SimpleAnimationObjectBridge", "unused six-frame script route"),
        "bhvUnusedFakeStar": ("UnusedFakeStarObjectBridge", "unused fake-star rotation route"),
        "bhvCloudPart": ("CloudPartObjectBridge", "cloud child transform/scale route"),
        "bhvCloud": ("CloudObjectBridge", "cloud parent action/child route"),
        "bhvBreakBoxTriangle": ("BreakBoxTriangleObjectBridge", "break-box triangle physics route"),
        "bhvCannonBaseUnused": ("CannonBaseUnusedObjectBridge", "unused cannon base animation route"),
        "bhvUnused05A8": ("NoOpObjectBridge", "break-only no-op route"),
        "bhvUnused1820": ("NoOpObjectBridge", "break-only no-op route"),
        "bhvUnused1F30": ("NoOpObjectBridge", "break-only no-op route"),
        "bhvUnused2A10": ("NoOpObjectBridge", "break-only no-op route"),
        "bhvUnused2A54": ("NoOpObjectBridge", "break-only no-op route"),
        "bhvInstantActiveWarp": ("NoOpObjectBridge", "break-only instant-active warp route"),
        "bhvAirborneWarp": ("NoOpObjectBridge", "break-only airborne warp route"),
        "bhvHardAirKnockBackWarp": ("NoOpObjectBridge", "break-only hard-air warp route"),
        "bhvSpinAirborneCircleWarp": ("NoOpObjectBridge", "break-only spin airborne circle warp route"),
        "bhvDeathWarp": ("NoOpObjectBridge", "break-only death warp route"),
        "bhvSpinAirborneWarp": ("NoOpObjectBridge", "break-only spin airborne warp route"),
        "bhvFlyingWarp": ("NoOpObjectBridge", "break-only flying warp route"),
        "bhvPaintingStarCollectWarp": ("NoOpObjectBridge", "break-only painting star warp route"),
        "bhvPaintingDeathWarp": ("NoOpObjectBridge", "break-only painting death warp route"),
        "bhvAirborneDeathWarp": ("NoOpObjectBridge", "break-only airborne death warp route"),
        "bhvAirborneStarCollectWarp": ("NoOpObjectBridge", "break-only airborne star warp route"),
        "bhvLaunchStarCollectWarp": ("NoOpObjectBridge", "break-only launch star warp route"),
        "bhvLaunchDeathWarp": ("NoOpObjectBridge", "break-only launch death warp route"),
        "bhvSwimmingWarp": ("NoOpObjectBridge", "break-only swimming warp route"),
        "bhvInsideCannon": ("NoOpObjectBridge", "break-only inside-cannon route"),
        "bhvSnowBall": ("NoOpObjectBridge", "break-only snow-ball route"),
        "bhvCannonBarrelBubbles": ("CannonBarrelBubblesObjectBridge", "cannon barrel water-bomb child route"),
        "bhvBubbleMaybe": ("BubbleMaybeObjectBridge", "water-air bubble child oscillation route"),
        "bhvWind": ("WindObjectBridge", "wind mist particle movement route"),
        "bhvJetStream": ("JetStreamObjectBridge", "jet-stream bubble/sound environment route"),
        "bhvJetStreamWaterRing": ("JetStreamWaterRingObjectBridge", "jet-stream water-ring collect/fade route"),
        "bhvJetStreamRingSpawner": ("JetStreamRingSpawnerObjectBridge", "jet-stream five-ring cadence/spawner route"),
        "bhvMantaRayWaterRing": ("MantaRayWaterRingObjectBridge", "Manta Ray water-ring collect/fade route"),
        "bhvWhirlpool": ("WhirlpoolObjectBridge", "whirlpool visibility/bubble/rotation route"),
        "bhvMantaRay": ("MantaRayObjectBridge", "Manta Ray trajectory/ring owner route"),
        "bhvShallowWaterWave": ("ShallowWaterWaveObjectBridge", "shallow-water droplet spawner route"),
        "bhvShallowWaterSplash": ("ShallowWaterWaveObjectBridge", "shallow-water splash droplet spawner route"),
        "bhvWaterSplash": ("WaterSplashSpawnerObjectBridge", "large water splash droplet spawner route"),
        "bhvMoneybag": ("MoneybagObjectBridge", "Moneybag value/owner route"),
        "bhvMoneybagHidden": ("MoneybagObjectBridge", "hidden Moneybag coin owner route"),
        "bhvMrI": ("MrIObjectBridge", "Mr. I value/owner route"),
        "bhvMrIBlueCoin": ("MrIObjectBridge", "Mr. I blue-coin reward child route"),
        "bhvMrIBody": ("MrIObjectBridge", "Mr. I iris child owner route"),
        "bhvMrIParticle": ("MrIObjectBridge", "Mr. I particle child owner route"),
        "bhvPiranhaPlant": ("PiranhaPlantObjectBridge", "Piranha Plant value/owner route"),
        "bhvPokey": ("PokeyObjectBridge", "Pokey value/owner route"),
        "bhvPokeyBodyPart": ("PokeyObjectBridge", "Pokey body-part child owner route"),
        "bhvRacingPenguin": ("RacingPenguinObjectBridge", "racing penguin path/owner route"),
        "bhvPenguinRaceFinishLine": ("RacingPenguinObjectBridge", "racing penguin finish-line child route"),
        "bhvPenguinRaceShortcutCheck": ("RacingPenguinObjectBridge", "racing penguin shortcut child route"),
        "bhvRespawner": ("RespawnerObjectBridge", "respawner value/owner route"),
        "bhvSmallBully": ("BullyObjectBridge", "Bully small variant owner route"),
        "bhvSmallChillBully": ("BullyObjectBridge", "Chief Chilly small-bully owner route"),
        "bhvScuttlebug": ("ScuttlebugObjectBridge", "Scuttlebug value/owner route"),
        "bhvScuttlebugSpawn": ("ScuttlebugObjectBridge", "Scuttlebug proximity spawner owner route"),
        "bhvSkeeter": ("SkeeterObjectBridge", "Skeeter value/owner route"),
        "bhvSkeeterWave": ("SkeeterObjectBridge", "Skeeter wave child route"),
        "bhvSnufitBalls": ("SnufitObjectBridge", "Snufit bullet child owner route"),
        "bhvSLWalkingPenguin": ("SLWalkingPenguinObjectBridge", "walking penguin value/owner route"),
        "bhvSnufit": ("SnufitObjectBridge", "Snufit value/owner route"),
        "bhvSnufitBullet": ("SnufitObjectBridge", "Snufit bullet owner route"),
        "bhvSpiny": ("SpinyObjectBridge", "Spiny value/owner route"),
        "bhvSpinyBall": ("SpinyObjectBridge", "Spiny ball owner route"),
        "bhvSwoop": ("SwoopObjectBridge", "Swoop value/owner route"),
        "bhvTuxiesMother": ("TuxiesMotherObjectBridge", "Tuxie's mother value/owner route"),
        "bhvPenguinBaby": ("TuxiesMotherObjectBridge", "Tuxie's mother baby-child terminal route"),
        "bhvUnused20E0": ("TuxiesMotherObjectBridge", "Tuxie's mother unused-child terminal route"),
        "bhvSmallPenguin": ("SmallPenguinObjectBridge", "small penguin value/owner route"),
        "bhvWaterBomb": ("WaterBombObjectBridge", "water bomb value/owner route"),
        "bhvWaterBombShadow": ("WaterBombObjectBridge", "water bomb shadow child route"),
        "bhvWaterBombSpawner": ("WaterBombObjectBridge", "water bomb spawner owner route"),
        "bhvWhomp": ("WhompObjectBridge", "Whomp value/owner route"),
        "bhvWhompKingBoss": ("WhompObjectBridge", "King Whomp variant owner route"),
        "bhvSmallWhomp": ("WhompObjectBridge", "small Whomp variant owner route"),
        "bhvMerryGoRoundBigBoo": ("BigBooObjectBridge", "Merry-Go-Round Big Boo variant owner route"),
        "bhvCirclingAmp": ("AmpObjectBridge", "circling Amp variant owner route"),
        "bhvDecorativePendulum": ("DecorativePendulumObjectBridge", "decorative pendulum value/owner route"),
        "bhvWoodenPost": ("ChainChompReleaseObjectBridge", "wooden-post release owner route"),
        "bhvYoshi": ("YoshiObjectBridge", "Yoshi value/owner route"),
    ]

    static func main() {
        do {
            try run(arguments: Array(CommandLine.arguments.dropFirst()))
        } catch {
            FileHandle.standardError.write(Data("sm64-behavior-manifest: \(error)\n".utf8))
            exit(2)
        }
    }

    private static func run(arguments: [String]) throws {
        let options = try parse(arguments: arguments)
        let reachability = try String(contentsOfFile: options.reachability, encoding: .utf8)
        var rows: [ManifestRow] = []
        var seen: Set<String> = []
        for line in reachability.split(whereSeparator: \.isNewline) {
            if line.hasPrefix("#") { continue }
            let fields = line.split(separator: "|", omittingEmptySubsequences: false).map(String.init)
            guard fields.count == 5, fields[0] == "behavior" else { continue }
            let identity = fields[1]
            let source = fields[2]
            guard !identity.isEmpty, !source.isEmpty else {
                throw ManifestError.invalidReachabilityRow(String(line))
            }
            let key = identity + "|" + source
            guard seen.insert(key).inserted else {
                throw ManifestError.duplicateRow(key)
            }
            if let route = swiftRoutes[identity] {
                rows.append(ManifestRow(
                    identity: identity,
                    source: source,
                    mapping: "swift_value_owner",
                    owner: route.owner,
                    reason: route.reason
                ))
            } else {
                rows.append(ManifestRow(
                    identity: identity,
                    source: source,
                    mapping: "unmigrated_c_adapter",
                    owner: "CBehaviorAdapter",
                    reason: "reachable behavior has no registered Swift value/owner route"
                ))
            }
        }

        let ordered = rows.sorted()
        let header = [
            "# sm64-modern-behavior-coverage-v1",
            "# identity|source|mapping|owner|reason",
        ]
        let output = (header + ordered.map(\.encoded)).joined(separator: "\n") + "\n"
        do {
            let outputURL = URL(fileURLWithPath: options.output).standardizedFileURL
            try FileManager.default.createDirectory(
                at: outputURL.deletingLastPathComponent(),
                withIntermediateDirectories: true
            )
            try Data(output.utf8).write(to: outputURL, options: .atomic)
        } catch {
            throw ManifestError.outputFailed("cannot write \(options.output): \(error)")
        }

        var fingerprint = UInt64(1_469_598_103_934_665_603)
        for byte in output.utf8 {
            fingerprint ^= UInt64(byte)
            fingerprint &*= UInt64(1_099_511_628_211)
        }
        let swiftCount = ordered.filter { $0.mapping == "swift_value_owner" }.count
        let adapterCount = ordered.filter { $0.mapping == "unmigrated_c_adapter" }.count
        print(String(format: "behaviorManifestFingerprint=0x%016llx", fingerprint))
        print("SM64 Modern behavior manifest rows=\(ordered.count) swiftValueOwner=\(swiftCount) unmigratedCAdapter=\(adapterCount)")
    }

    private static func parse(arguments: [String]) throws -> Options {
        var values: [String: String] = [:]
        var index = 0
        while index < arguments.count {
            guard index + 1 < arguments.count, arguments[index].hasPrefix("--") else {
                throw ManifestError.invalidArguments("usage: sm64-behavior-manifest --reachability TSV --output TSV")
            }
            values[arguments[index]] = arguments[index + 1]
            index += 2
        }
        guard let reachability = values["--reachability"], let output = values["--output"] else {
            throw ManifestError.invalidArguments("usage: sm64-behavior-manifest --reachability TSV --output TSV")
        }
        return Options(reachability: reachability, output: output)
    }
}
