import Foundation
struct SM64BetaTrampolineObjectEffectRecord: Equatable, Sendable { let objectID: SM64ObjectID; let role: SM64BetaTrampolineRole; let output: SM64BetaTrampolineOutput; let spawnedSpring: SM64ObjectID? }
final class SM64BetaTrampolineObjectBridge {
    static let topBehaviorIdentity: UInt64 = 0x6268_765F_627474
    static let springBehaviorIdentity: UInt64 = 0x6268_765F_627473
    private var roles:[SM64ObjectID:SM64BetaTrampolineRole]=[:];private var parents:[SM64ObjectID:SM64ObjectID]=[:];private(set) var effectLog:[SM64BetaTrampolineObjectEffectRecord]=[];private var marioOn:Set<SM64ObjectID>=[]
    var registeredIDs:[SM64ObjectID]{roles.keys.sorted{$0.slot == $1.slot ? $0.generation < $1.generation : $0.slot < $1.slot}}
    func beginExternalTick(){effectLog.removeAll(keepingCapacity:true)}
    @discardableResult func spawnTop(in engineState:SM64SwiftEngineState,position:SM64ObjectVector3 = .zero,marioOn:Bool=false)throws->SM64ObjectID{let id=try engineState.spawnObject(in:.surface,behaviorIdentity:Self.topBehaviorIdentity);guard attach(id,role:.top,position:position,parent:nil,in:engineState.objects)else{_ = engineState.objects.despawn(id);preconditionFailure("newly spawned beta trampoline top could not attach")};if marioOn{self.marioOn.insert(id)};return id}
    @discardableResult func attach(_ id:SM64ObjectID,role:SM64BetaTrampolineRole,position:SM64ObjectVector3,parent:SM64ObjectID?,in pool:SM64ObjectPool)->Bool{guard pool.record(for:id) != nil else{return false};if let parent{guard pool.record(for:parent) != nil else{return false};parents[id]=parent};roles[id]=role;return pool.mutate(id){r in r.position=position;r.homePosition=position;r.objectFlags |= SM64ObjectScheduler.objectFlagUpdateGfxPositionAndAngle|SM64ObjectScheduler.objectFlagBuildTransform}}
    @discardableResult func setMarioOn(_ value:Bool,for id:SM64ObjectID)->Bool{guard roles[id] == .top else{return false};if value{marioOn.insert(id)}else{marioOn.remove(id)};return true}
    @discardableResult func updateInline(_ id:SM64ObjectID,state engineState:SM64SwiftEngineState)->Bool{guard let role=roles[id],let r=engineState.objects.record(for:id)else{return false};let parent=parents[id].flatMap{engineState.objects.record(for:$0)};let o=SM64BetaTrampolineBehavior.update(role:role,timer:r.timer,position:r.position,homePosition:r.homePosition,faceAngles:r.faceAngles,parentPosition:parent?.position ?? r.position,parentFaceAngles:parent?.faceAngles ?? r.faceAngles,marioOn:marioOn.contains(id));var child:SM64ObjectID?;if o.spawnSpring{child=try? engineState.spawnObject(in:.default,behaviorIdentity:Self.springBehaviorIdentity,parent:id);if let child{parents[child]=id;roles[child] = .spring;_ = attach(child,role:.spring,position:o.position,parent:id,in:engineState.objects)}};_ = engineState.objects.mutate(id){n in n.position=o.position;n.faceAngles=o.faceAngles;n.scale.y=o.scaleY;n.timer &+= 1;n.objectFlags |= SM64ObjectScheduler.objectFlagUpdateGfxPositionAndAngle|SM64ObjectScheduler.objectFlagBuildTransform};effectLog.append(.init(objectID:id,role:role,output:o,spawnedSpring:child));return true}
    func remove(_ id:SM64ObjectID){roles.removeValue(forKey:id);parents.removeValue(forKey:id);marioOn.remove(id)}
    func pruneExternal(unloaded:[SM64ObjectID],pool:SM64ObjectPool){for id in unloaded{remove(id)};for id in registeredIDs where pool.record(for:id)==nil{remove(id)}}
}
