import Foundation
struct SM64BetaChestObjectEffectRecord: Equatable, Sendable { let objectID: SM64ObjectID; let role: SM64BetaChestRole; let output: SM64BetaChestOutput; let spawnedChild: SM64ObjectID? }
final class SM64BetaChestObjectBridge {
    static let bottomBehaviorIdentity: UInt64 = 0x6268_765F_626362
    static let lidBehaviorIdentity: UInt64 = 0x6268_765F_62636C
    private let waterAirBubbleBridge: SM64WaterAirBubbleObjectBridge
    private var roles:[SM64ObjectID:SM64BetaChestRole]=[:]
    private(set) var effectLog:[SM64BetaChestObjectEffectRecord]=[]
    init(waterAirBubbleBridge:SM64WaterAirBubbleObjectBridge){self.waterAirBubbleBridge=waterAirBubbleBridge}
    var registeredIDs:[SM64ObjectID]{roles.keys.sorted{$0.slot == $1.slot ? $0.generation < $1.generation : $0.slot < $1.slot}}
    func beginExternalTick(){effectLog.removeAll(keepingCapacity:true)}
    @discardableResult func spawnBottom(in engineState:SM64SwiftEngineState,position:SM64ObjectVector3 = .zero)throws->SM64ObjectID{let bottom=try engineState.spawnObject(in:.default,behaviorIdentity:Self.bottomBehaviorIdentity);guard attach(bottom,role:.bottom,position:position,parent:nil,in:engineState.objects)else{_ = engineState.objects.despawn(bottom);preconditionFailure("newly spawned beta chest bottom could not attach")};let lid=try engineState.spawnObject(in:.default,behaviorIdentity:Self.lidBehaviorIdentity,parent:bottom);guard attach(lid,role:.lid,position:position,parent:bottom,in:engineState.objects)else{_ = engineState.objects.despawn(lid);preconditionFailure("newly spawned beta chest lid could not attach")};return bottom}
    @discardableResult func attach(_ id:SM64ObjectID,role:SM64BetaChestRole,position:SM64ObjectVector3,parent:SM64ObjectID?,in pool:SM64ObjectPool)->Bool{guard pool.record(for:id) != nil else{return false};if let parent{guard pool.record(for:parent) != nil else{return false}};roles[id]=role;return pool.mutate(id){r in r.position=position;r.homePosition=position;if role == .bottom{r.hitboxRadius=200;r.hitboxHeight=200;r.interactionType=0}else{r.parentRelativePosition=SM64ObjectVector3(x:0,y:97,z:-77);r.objectFlags |= SM64ObjectScheduler.objectFlagTransformRelativeToParent;r.faceAngles.pitch=0;r.action=0;r.timer=0};r.objectFlags |= SM64ObjectScheduler.objectFlagUpdateGfxPositionAndAngle|SM64ObjectScheduler.objectFlagBuildTransform}}
    @discardableResult func updateInline(_ id:SM64ObjectID,state engineState:SM64SwiftEngineState)->Bool{guard let role=roles[id],let r=engineState.objects.record(for:id)else{return false};if role == .bottom{effectLog.append(.init(objectID:id,role:role,output:.init(action:.closed,timer:r.timer,facePitch:r.faceAngles.pitch,spawnBubble:false,playSound:false),spawnedChild:nil));return true};let o=SM64BetaChestBehavior.update(action:SM64BetaChestAction(rawValue:UInt8(clamping:r.action)) ?? .closed,timer:r.timer,distanceToMario:r.distanceToMario,facePitch:r.faceAngles.pitch);var child:SM64ObjectID?;if o.spawnBubble{child=try? waterAirBubbleBridge.spawnBubble(in:engineState,position:SM64ObjectVector3(x:r.position.x,y:r.position.y-80,z:r.position.z+120),waterLevel:100)};_ = engineState.objects.mutate(id){n in n.action=Int32(o.action.rawValue);n.timer=o.timer;n.faceAngles.pitch=o.facePitch;n.interactionStatus=0;n.objectFlags |= SM64ObjectScheduler.objectFlagUpdateGfxPositionAndAngle|SM64ObjectScheduler.objectFlagBuildTransform};effectLog.append(.init(objectID:id,role:role,output:o,spawnedChild:child));return true}
    func remove(_ id:SM64ObjectID){roles.removeValue(forKey:id)}
    func pruneExternal(unloaded:[SM64ObjectID],pool:SM64ObjectPool){for id in unloaded{remove(id)};for id in registeredIDs where pool.record(for:id)==nil{remove(id)}}
}
