import Foundation
struct SM64BowserTailAnchorObjectEffectRecord: Equatable, Sendable { let objectID: SM64ObjectID; let output: SM64BowserTailAnchorOutput; let parent: SM64ObjectID }
final class SM64BowserTailAnchorObjectBridge {
    static let defaultBehaviorIdentity: UInt64 = 0x6268_765F_746261_31
    private var parents:[SM64ObjectID:SM64ObjectID]=[:];private var collided:Set<SM64ObjectID>=[];private(set) var effectLog:[SM64BowserTailAnchorObjectEffectRecord]=[]
    var registeredIDs:[SM64ObjectID]{parents.keys.sorted{$0.slot == $1.slot ? $0.generation < $1.generation : $0.slot < $1.slot}}
    func beginExternalTick(){effectLog.removeAll(keepingCapacity:true)}
    @discardableResult func spawn(in engineState:SM64SwiftEngineState,parent:SM64ObjectID,position:SM64ObjectVector3 = .zero)throws->SM64ObjectID{let id=try engineState.spawnObject(in:.generalActor,behaviorIdentity:Self.defaultBehaviorIdentity,parent:parent);guard attach(id,parent:parent,position:position,in:engineState.objects)else{_ = engineState.objects.despawn(id);preconditionFailure("newly spawned Bowser tail anchor could not attach")};return id}
    @discardableResult func attach(_ id:SM64ObjectID,parent:SM64ObjectID,position:SM64ObjectVector3,in pool:SM64ObjectPool)->Bool{guard pool.record(for:id) != nil,pool.record(for:parent) != nil else{return false};parents[id]=parent;return pool.mutate(id){r in r.position=position;r.parentRelativePosition.x=90;r.hitboxRadius=100;r.hitboxHeight=50;r.hitboxDownOffset = -50;r.interactionType=1<<3;r.intangibleTimer=0;r.objectFlags |= SM64ObjectScheduler.objectFlagUpdateGfxPositionAndAngle|SM64ObjectScheduler.objectFlagBuildTransform}}
    @discardableResult func setCollision(_ value:Bool,for id:SM64ObjectID)->Bool{guard parents[id] != nil else{return false};if value{collided.insert(id)}else{collided.remove(id)};return true}
    @discardableResult func updateInline(_ id:SM64ObjectID,state engineState:SM64SwiftEngineState)->Bool{guard let parent=parents[id],let r=engineState.objects.record(for:id),let p=engineState.objects.record(for:parent)else{return false};let action=SM64BowserTailAnchorAction(rawValue:UInt8(clamping:r.action)) ?? .tangible;let o=SM64BowserTailAnchorBehavior.update(action:action,timer:r.timer,parentAction:p.action,parentIntangibleTimer:p.intangibleTimer,collided:collided.remove(id) != nil);_ = engineState.objects.mutate(parent){$0.intangibleTimer=o.parentIntangibleTimer};_ = engineState.objects.mutate(id){n in n.parentRelativePosition.x=o.parentRelativeX;n.interactionType=o.tangible ? (1<<3):0;n.interactionStatus=0;n.intangibleTimer=o.tangible ? 0:1;n.action=Int32(o.action.rawValue);n.objectFlags |= SM64ObjectScheduler.objectFlagUpdateGfxPositionAndAngle|SM64ObjectScheduler.objectFlagBuildTransform};effectLog.append(.init(objectID:id,output:o,parent:parent));return true}
    func remove(_ id:SM64ObjectID){parents.removeValue(forKey:id);collided.remove(id)}
    func pruneExternal(unloaded:[SM64ObjectID],pool:SM64ObjectPool){for id in unloaded{remove(id)};for id in registeredIDs where pool.record(for:id)==nil{remove(id)}}
}
