import Foundation

struct SM64CastleFloorTrapObjectEffectRecord: Equatable, Sendable { let objectID: SM64ObjectID; let output: SM64CastleFloorTrapOutput; let spawnedChildren: [SM64ObjectID] }
final class SM64CastleFloorTrapObjectBridge {
    static let parentBehaviorIdentity: UInt64 = 0x6268_765F_636674
    static let childBehaviorIdentity: UInt64 = 0x6268_765F_666974
    private struct State { let role: SM64CastleFloorTrapRole; var interactTurn: Bool; var marioActionExit: Bool; var marioOnPlatform: Bool; var marioDistance: Float; var parent: SM64ObjectID? }
    private var states: [SM64ObjectID: State] = [:]; private(set) var effectLog: [SM64CastleFloorTrapObjectEffectRecord] = []
    var registeredIDs: [SM64ObjectID] { states.keys.sorted { $0.slot == $1.slot ? $0.generation < $1.generation : $0.slot < $1.slot } }
    func beginExternalTick() { effectLog.removeAll(keepingCapacity: true) }
    @discardableResult
    func spawnParent(in engineState: SM64SwiftEngineState, position: SM64ObjectVector3 = .zero) throws -> SM64ObjectID { let id = try engineState.spawnObject(in: .default, behaviorIdentity: Self.parentBehaviorIdentity); guard attach(id, role: .parent, position: position, parent: nil, in: engineState.objects) else { _ = engineState.objects.despawn(id); preconditionFailure("newly spawned castle trap parent could not attach") }; return id }
    @discardableResult
    func spawnChild(in engineState: SM64SwiftEngineState, parent: SM64ObjectID, position: SM64ObjectVector3 = .zero) throws -> SM64ObjectID { let id = try engineState.spawnObject(in: .surface, behaviorIdentity: Self.childBehaviorIdentity, parent: parent); guard attach(id, role: .child, position: position, parent: parent, in: engineState.objects) else { _ = engineState.objects.despawn(id); preconditionFailure("newly spawned castle trap child could not attach") }; return id }
    @discardableResult
    func attach(_ id: SM64ObjectID, role: SM64CastleFloorTrapRole, position: SM64ObjectVector3, parent: SM64ObjectID?, in pool: SM64ObjectPool) -> Bool { guard pool.record(for: id) != nil else { return false }; states[id] = State(role: role, interactTurn: false, marioActionExit: false, marioOnPlatform: false, marioDistance: 0, parent: parent); return pool.mutate(id) { record in record.position = position; record.parent = parent ?? record.parent; record.collisionDistance = role == .child ? 1000 : 0; record.objectFlags |= SM64ObjectScheduler.objectFlagUpdateGfxPositionAndAngle | SM64ObjectScheduler.objectFlagBuildTransform } }
    @discardableResult
    func setInputs(for id: SM64ObjectID, interactTurn: Bool? = nil, marioActionExit: Bool? = nil, marioOnPlatform: Bool? = nil, marioDistance: Float? = nil) -> Bool { guard var state = states[id] else { return false }; if let interactTurn { state.interactTurn = interactTurn }; if let marioActionExit { state.marioActionExit = marioActionExit }; if let marioOnPlatform { state.marioOnPlatform = marioOnPlatform }; if let marioDistance { state.marioDistance = marioDistance }; states[id] = state; return true }
    @discardableResult
    func updateInline(_ id: SM64ObjectID, state engineState: SM64SwiftEngineState) -> Bool { guard var state = states[id], let record = engineState.objects.record(for: id) else { return false }; let parentRoll = state.parent.flatMap { engineState.objects.record(for: $0)?.faceAngles.roll } ?? record.faceAngles.roll; let output = SM64CastleFloorTrapBehavior.update(.init(role: state.role, action: record.action, timer: record.timer, roll: record.faceAngles.roll, angleVelocity: record.angleVelocity.roll, interactTurn: state.interactTurn, marioActionExit: state.marioActionExit, marioOnPlatform: state.marioOnPlatform, marioDistance: state.marioDistance, parentRoll: parentRoll)); state.interactTurn = false; state.marioActionExit = false; state.marioOnPlatform = false; states[id] = state; var children: [SM64ObjectID] = []; if output.role == .parent && record.timer == 0, let childA = try? spawnChild(in: engineState, parent: id, position: SM64ObjectVector3(x: record.position.x - 358, y: record.position.y, z: record.position.z)), let childB = try? spawnChild(in: engineState, parent: id, position: SM64ObjectVector3(x: record.position.x + 358, y: record.position.y, z: record.position.z)) { children = [childA, childB] }; _ = engineState.objects.mutate(id) { next in next.action = output.action; next.timer = output.timer; next.faceAngles.roll = output.roll; next.angleVelocity.roll = output.angleVelocity; if output.role == .child { next.intangibleTimer = -1 }; next.objectFlags |= SM64ObjectScheduler.objectFlagUpdateGfxPositionAndAngle | SM64ObjectScheduler.objectFlagBuildTransform }; effectLog.append(.init(objectID: id, output: output, spawnedChildren: children)); return true }
    func remove(_ id: SM64ObjectID) { states.removeValue(forKey: id) }
    func pruneExternal(unloaded: [SM64ObjectID], pool: SM64ObjectPool) { for id in unloaded { remove(id) }; for id in registeredIDs where pool.record(for: id) == nil { remove(id) } }
}
