import Foundation

struct SM64FishObjectEffectRecord: Equatable, Sendable {
    let objectID: SM64ObjectID
    let role: SM64FishRole
    let groupOutput: SM64FishGroupOutput?
    let fishOutput: SM64FishOutput?
    let spawnedChildren: [SM64ObjectID]
}

final class SM64FishObjectBridge {
    static let fishBehaviorIdentity: UInt64 = 0x6268_765F_666973
    static let fishGroupBehaviorIdentity: UInt64 = 0x6268_765F_666770
    static let fish2BehaviorIdentity: UInt64 = 0x6268_765F_666732
    static let fish3BehaviorIdentity: UInt64 = 0x6268_765F_666733
    static let largeFishGroupBehaviorIdentity: UInt64 = 0x6268_765F_6C6667
    static let fishModel: UInt32 = 0x65 // MODEL_FISH
    private struct State { let role: SM64FishRole; var variant: SM64FishVariant; var secretAquarium: Bool; var parent: SM64ObjectID?; var parentDuplicate: Bool; var distanceToMario: Float; var angleToMario: Int32; var angleToHome: Int32 }
    private var states:[SM64ObjectID:State]=[:]; private(set) var effectLog:[SM64FishObjectEffectRecord]=[]
    var registeredIDs:[SM64ObjectID]{states.keys.sorted{$0.slot == $1.slot ? $0.generation < $1.generation : $0.slot < $1.slot}}
    func beginExternalTick(){effectLog.removeAll(keepingCapacity:true)}
    @discardableResult func spawnGroup(in engineState:SM64SwiftEngineState,variant:SM64FishVariant = .blue20,position:SM64ObjectVector3 = .zero,distanceToMario:Float = 10_000,secretAquarium:Bool=false,identity:UInt64?=nil)throws->SM64ObjectID{let behavior=identity ?? (variant == .blue20 ? Self.fishGroupBehaviorIdentity : variant == .blue5 ? Self.fish2BehaviorIdentity : variant == .cyan20 ? Self.largeFishGroupBehaviorIdentity : Self.fish3BehaviorIdentity);let id=try engineState.spawnObject(in:.default,behaviorIdentity:behavior);guard attachGroup(id,variant:variant,position:position,distanceToMario:distanceToMario,secretAquarium:secretAquarium,in:engineState.objects)else{_ = engineState.objects.despawn(id);preconditionFailure("newly spawned fish group could not attach")};return id}
    @discardableResult func attachGroup(_ id:SM64ObjectID,variant:SM64FishVariant,position:SM64ObjectVector3,distanceToMario:Float,secretAquarium:Bool,in pool:SM64ObjectPool)->Bool{guard pool.record(for:id) != nil else{return false};states[id]=State(role:.group,variant:variant,secretAquarium:secretAquarium,parent:nil,parentDuplicate:false,distanceToMario:distanceToMario,angleToMario:0,angleToHome:0);return pool.mutate(id){r in r.position=position;r.homePosition=position;r.distanceToMario=distanceToMario;r.objectFlags |= SM64ObjectScheduler.objectFlagUpdateGfxPositionAndAngle|SM64ObjectScheduler.objectFlagBuildTransform}}
    @discardableResult func spawnFish(in engineState:SM64SwiftEngineState,parent:SM64ObjectID?=nil,position:SM64ObjectVector3 = .zero,variant:SM64FishVariant = .blue20)throws->SM64ObjectID{let id=try engineState.spawnObject(in:.default,model:Self.fishModel,behaviorIdentity:Self.fishBehaviorIdentity,parent:parent);guard attachFish(id,variant:variant,parent:parent,position:position,in:engineState.objects)else{_ = engineState.objects.despawn(id);preconditionFailure("newly spawned fish could not attach")};return id}
    @discardableResult func attachFish(_ id:SM64ObjectID,variant:SM64FishVariant,parent:SM64ObjectID?,position:SM64ObjectVector3,in pool:SM64ObjectPool)->Bool{guard pool.record(for:id) != nil else{return false};states[id]=State(role:.fish,variant:variant,secretAquarium:false,parent:parent,parentDuplicate:false,distanceToMario:10_000,angleToMario:0,angleToHome:0);return pool.mutate(id){r in r.position=position;r.homePosition=position;r.forwardVelocity=3;r.objectFlags |= SM64ObjectScheduler.objectFlagUpdateGfxPositionAndAngle|SM64ObjectScheduler.objectFlagBuildTransform}}
    @discardableResult func setGroupInput(distanceToMario:Float,secretAquarium:Bool=false,for id:SM64ObjectID)->Bool{guard var s=states[id],s.role == .group else{return false};s.distanceToMario=distanceToMario;s.secretAquarium=secretAquarium;states[id]=s;return true}
    @discardableResult func setFishInput(distanceToMario:Float,angleToMario:Int32=0,angleToHome:Int32=0,parentDuplicate:Bool=false,for id:SM64ObjectID)->Bool{guard var s=states[id],s.role == .fish else{return false};s.distanceToMario=distanceToMario;s.angleToMario=angleToMario;s.angleToHome=angleToHome;s.parentDuplicate=parentDuplicate;states[id]=s;return true}
    @discardableResult func updateInline(_ id:SM64ObjectID,state engineState:SM64SwiftEngineState)->Bool{guard var s=states[id],let record=engineState.objects.record(for:id)else{return false};if s.role == .group{let o=SM64FishBehavior.updateGroup(action:record.action,variant:s.variant,distanceToMario:s.distanceToMario,secretAquarium:s.secretAquarium);var children:[SM64ObjectID]=[];if o.spawnedChildren>0{for _ in 0..<o.spawnedChildren{if let child=try? spawnFish(in:engineState,parent:id,position:record.position,variant:o.variant){children.append(child)}}};_ = engineState.objects.mutate(id){$0.action=o.action};effectLog.append(.init(objectID:id,role:.group,groupOutput:o,fishOutput:nil,spawnedChildren:children));s.distanceToMario=10_000;states[id]=s;return true};let parentDuplicate=s.parentDuplicate || s.parent.flatMap{engineState.objects.record(for:$0)?.action == 2} == true;let o=SM64FishBehavior.updateFish(action:record.action,timer:record.timer,position:record.position,moveYaw:record.moveAngles.yaw,forwardVelocity:record.forwardVelocity,targetY:record.position.y+100,angleToMario:s.angleToMario,angleToHome:s.angleToHome,parentDuplicate:parentDuplicate);s.parentDuplicate=false;s.distanceToMario=10_000;states[id]=s;_ = engineState.objects.mutate(id){n in n.action=o.action;n.timer=o.timer;n.position=o.position;n.moveAngles.yaw=o.moveYaw;n.forwardVelocity=o.forwardVelocity;n.animationState=Int32(o.animationAcceleration*100);if o.shouldDelete{n.activeFlags=0};n.objectFlags |= SM64ObjectScheduler.objectFlagUpdateGfxPositionAndAngle|SM64ObjectScheduler.objectFlagBuildTransform};effectLog.append(.init(objectID:id,role:.fish,groupOutput:nil,fishOutput:o,spawnedChildren:[]));return true}
    func remove(_ id:SM64ObjectID){states.removeValue(forKey:id)};func pruneExternal(unloaded:[SM64ObjectID],pool:SM64ObjectPool){for id in unloaded{remove(id)};for id in registeredIDs where pool.record(for:id)==nil{remove(id)}}
}
