import Foundation

struct SM64BlackSmokeMarioObjectEffectRecord: Equatable, Sendable { let objectID: SM64ObjectID; let output: SM64BlackSmokeMarioOutput }
struct SM64FlameMarioObjectEffectRecord: Equatable, Sendable { let objectID: SM64ObjectID; let output: SM64FlameMarioOutput; let spawnedSmoke: SM64ObjectID? }

final class SM64BlackSmokeMarioObjectBridge {
    static let defaultBehaviorIdentity: UInt64 = 0x6268_765F_626D31
    private struct State { let initialMoveYaw: Int32; let initialForwardVelocity: Float; let initialVelocityY: Float; let angleVelocityYaw: Int32; var moveYaw: Int32; var forwardVelocity: Float; var velocityY: Float }
    private var states: [SM64ObjectID: State] = [:]
    private(set) var effectLog: [SM64BlackSmokeMarioObjectEffectRecord] = []
    var registeredIDs: [SM64ObjectID] { states.keys.sorted { $0.slot == $1.slot ? $0.generation < $1.generation : $0.slot < $1.slot } }
    func beginExternalTick() { effectLog.removeAll(keepingCapacity: true) }
    @discardableResult func spawnSmoke(in engineState: SM64SwiftEngineState, position: SM64ObjectVector3 = .zero, marioPosition: SM64ObjectVector3 = .zero, marioYaw: Int32 = 0, initialMoveYaw: Int32 = 0, initialForwardVelocity: Float = 1, initialVelocityY: Float = 8, parent: SM64ObjectID? = nil) throws -> SM64ObjectID { let id=try engineState.spawnObject(in:.unimportant,behaviorIdentity:Self.defaultBehaviorIdentity,parent:parent); guard attach(id,position:position,marioPosition:marioPosition,marioYaw:marioYaw,initialMoveYaw:initialMoveYaw,initialForwardVelocity:initialForwardVelocity,initialVelocityY:initialVelocityY,in:engineState.objects) else{_ = engineState.objects.despawn(id);preconditionFailure("newly spawned black smoke could not attach")}; return id }
    @discardableResult func attach(_ id: SM64ObjectID, position: SM64ObjectVector3, marioPosition: SM64ObjectVector3, marioYaw: Int32, initialMoveYaw: Int32, initialForwardVelocity: Float, initialVelocityY: Float, in pool: SM64ObjectPool) -> Bool { guard pool.record(for:id) != nil else{return false}; states[id]=State(initialMoveYaw:initialMoveYaw,initialForwardVelocity:initialForwardVelocity,initialVelocityY:initialVelocityY,angleVelocityYaw:0,moveYaw:initialMoveYaw,forwardVelocity:0,velocityY:0); return pool.mutate(id){r in r.position=position;r.homePosition=position;r.objectFlags |= SM64ObjectScheduler.objectFlagUpdateGfxPositionAndAngle|SM64ObjectScheduler.objectFlagBuildTransform} }
    @discardableResult func updateInline(_ id: SM64ObjectID,state engineState:SM64SwiftEngineState)->SM64BlackSmokeMarioObjectEffectRecord? { guard var s=states[id],let r=engineState.objects.record(for:id),let marioID=engineState.globals.marioObject,let mario=engineState.objects.record(for:marioID) else{return nil};let o=SM64BlackSmokeMarioBehavior.update(.init(position:r.position,marioPosition:mario.position,marioYaw:mario.moveAngles.yaw,moveYaw:s.moveYaw,forwardVelocity:s.forwardVelocity,velocityY:s.velocityY,timer:r.timer,initialMoveYaw:s.initialMoveYaw,initialForwardVelocity:s.initialForwardVelocity,initialVelocityY:s.initialVelocityY,angleVelocityYaw:s.angleVelocityYaw));s.moveYaw=o.moveYaw;s.forwardVelocity=o.forwardVelocity;s.velocityY=o.velocityY;states[id]=s;_ = engineState.objects.mutate(id){n in n.position=o.position;n.moveAngles.yaw=o.moveYaw;n.forwardVelocity=o.forwardVelocity;n.velocity.y=o.velocityY;n.timer=o.shouldDeactivate ? 24 : r.timer+1;if o.shouldDeactivate{n.activeFlags=0}};let e=SM64BlackSmokeMarioObjectEffectRecord(objectID:id,output:o);effectLog.append(e);return e }
    func remove(_ id:SM64ObjectID){states.removeValue(forKey:id)};func pruneExternal(unloaded:[SM64ObjectID],pool:SM64ObjectPool){for id in unloaded{remove(id)};for id in registeredIDs where pool.record(for:id)==nil{remove(id)}}
}

final class SM64FlameMarioObjectBridge {
    static let defaultBehaviorIdentity: UInt64 = 0x6268_765F_666D31
    static let particleFlag: UInt32 = 1 << 11
    private let blackSmokeBridge: SM64BlackSmokeMarioObjectBridge?
    private var states: Set<SM64ObjectID> = []
    private(set) var effectLog: [SM64FlameMarioObjectEffectRecord] = []
    init(blackSmokeBridge:SM64BlackSmokeMarioObjectBridge?=nil){self.blackSmokeBridge=blackSmokeBridge}
    var registeredIDs:[SM64ObjectID]{states.sorted{$0.slot == $1.slot ? $0.generation < $1.generation : $0.slot < $1.slot}};func beginExternalTick(){effectLog.removeAll(keepingCapacity:true)}
    @discardableResult func spawnFlame(in engineState:SM64SwiftEngineState,position:SM64ObjectVector3 = .zero,activeParticleFlags:UInt32=SM64FlameMarioObjectBridge.particleFlag,parent:SM64ObjectID?=nil)throws->SM64ObjectID{let id=try engineState.spawnObject(in:.default,behaviorIdentity:Self.defaultBehaviorIdentity,parent:parent);guard attach(id,position:position,activeParticleFlags:activeParticleFlags,in:engineState.objects)else{_ = engineState.objects.despawn(id);preconditionFailure("newly spawned Mario flame could not attach")};return id}
    @discardableResult func attach(_ id:SM64ObjectID,position:SM64ObjectVector3,activeParticleFlags:UInt32,in pool:SM64ObjectPool)->Bool{guard pool.record(for:id) != nil else{return false};states.insert(id);return pool.mutate(id){r in r.position=position;r.activeParticleFlags=activeParticleFlags;r.objectFlags |= SM64ObjectScheduler.objectFlagUpdateGfxPositionAndAngle|SM64ObjectScheduler.objectFlagBuildTransform}}
    @discardableResult func updateInline(_ id:SM64ObjectID,state engineState:SM64SwiftEngineState)->SM64FlameMarioObjectEffectRecord?{guard states.contains(id),let r=engineState.objects.record(for:id),let marioID=engineState.globals.marioObject,let mario=engineState.objects.record(for:marioID)else{return nil};let o=SM64FlameMarioBehavior.update(.init(marioPosition:mario.position,marioYaw:mario.moveAngles.yaw,timer:r.timer,activeParticleFlags:r.activeParticleFlags,particleFlag:Self.particleFlag));var smoke:SM64ObjectID?;if o.spawnSmoke{smoke=try?engineState.spawnObject(in:.unimportant,behaviorIdentity:SM64BlackSmokeMarioObjectBridge.defaultBehaviorIdentity,parent:id);if let smoke{_ = blackSmokeBridge?.attach(smoke,position:o.position,marioPosition:mario.position,marioYaw:mario.moveAngles.yaw,initialMoveYaw:mario.moveAngles.yaw,initialForwardVelocity:1,initialVelocityY:8,in:engineState.objects)}};_ = engineState.objects.mutate(id){n in n.position=o.position;n.scale = .init(x:o.scale,y:o.scale,z:o.scale);n.timer &+= 1;if o.clearParticleFlag{n.activeParticleFlags &= ~Self.particleFlag};if o.shouldDelete{n.activeFlags=0}};let e=SM64FlameMarioObjectEffectRecord(objectID:id,output:o,spawnedSmoke:smoke);effectLog.append(e);return e}
    func remove(_ id:SM64ObjectID){states.remove(id)};func pruneExternal(unloaded:[SM64ObjectID],pool:SM64ObjectPool){for id in unloaded{remove(id)};for id in registeredIDs where pool.record(for:id)==nil{remove(id)}}
}
