import Foundation

/// The six display-list routes accepted by `gdm_gettestdl` in
/// `src/goddard/renderer.c`.  These are source route IDs, not Metal texture
/// IDs and not pointers into the legacy object graph.
enum SM64MarioFaceGoddardRouteID: UInt32, CaseIterable, Sendable {
    case yoshiScene = 0
    case yoshiShell = 1
    case marioNormal = 2
    case marioGameOver = 3
    case carScene = 4
    case testnet2 = 5
}

enum SM64MarioFaceGoddardUpdateDomain: UInt32, Sendable {
    case none = 0
    case yoshiScene = 1
    case marioScene = 2
    case carScene = 3
}

enum SM64MarioFaceTextureFormat: UInt32, Sendable {
    case rgba16 = 1
    case ia8 = 2
}

enum SM64MarioFaceTextureFamily: UInt32, Sendable {
    case hand = 1
    case redStar = 2
    case whiteStar = 3
    case faceShine = 4
}

struct SM64MarioFaceTextureResource: Equatable, Sendable {
    let textureID: UInt32
    let symbol: String
    let includePath: String
    let format: SM64MarioFaceTextureFormat
    let bitsPerTexel: UInt32
    let width: UInt32
    let height: UInt32
    let frameIndex: UInt32
    let family: SM64MarioFaceTextureFamily
    /// Source sampler/material facts. Bit 0 = texture generation, bit 1 =
    /// bilinear filtering, bit 2 = wrap in both axes.
    let policyFlags: UInt32
}

struct SM64MarioFaceRouteRecord: Equatable, Sendable {
    let routeID: SM64MarioFaceGoddardRouteID
    let displayListID: UInt32
    let viewSymbol: String
    let objectSymbol: String
    let updateDomain: SM64MarioFaceGoddardUpdateDomain
    /// Bit 0 = route is the Mario-face path, bit 1 = hand view is updated,
    /// bit 2 = route allocates/updates a scene view.
    let policyFlags: UInt32
    let textureIDs: [UInt32]
}

struct SM64MarioFaceCameraOrientationRecord: Equatable, Sendable {
    let routeID: SM64MarioFaceGoddardRouteID
    let viewSymbol: String
    let viewportWidth: UInt32
    let viewportHeight: UInt32
    let rendererScale100000: UInt32
    let rendererPitchMinDegrees100: Int32
    let rendererPitchMaxDegrees100: Int32
    let mainScale100000: UInt32
    let mainPitchMinDegrees100: Int32
    let mainPitchMaxDegrees100: Int32
    let cursorX: UInt32
    let cursorY: UInt32
    let lightCount: UInt32
    let lightDirection: [Int32]
    let lightScaleRGB1000: [UInt32]
}

/// Source-backed route, texture, and camera facts.  The source texture bytes
/// are intentionally not copied here: ROM-derived/generated bytes remain in
/// the content-pack boundary, while this catalog records the exact include
/// symbol, dimensions, format, and sampler policy that a renderer must use.
enum SM64MarioFaceRouteResourceCatalog {
    static let textures: [SM64MarioFaceTextureResource] = [
        .init(
            textureID: 1, symbol: "gd_texture_hand_open",
            includePath: "textures/intro_raw/hand_open.rgba16.inc.c",
            format: .rgba16, bitsPerTexel: 16, width: 32, height: 32,
            frameIndex: 0, family: .hand, policyFlags: 0b110
        ),
        .init(
            textureID: 2, symbol: "gd_texture_hand_closed",
            includePath: "textures/intro_raw/hand_closed.rgba16.inc.c",
            format: .rgba16, bitsPerTexel: 16, width: 32, height: 32,
            frameIndex: 1, family: .hand, policyFlags: 0b110
        ),
        .init(
            textureID: 0x100, symbol: "gd_texture_red_star_0",
            includePath: "textures/intro_raw/red_star_0.rgba16.inc.c",
            format: .rgba16, bitsPerTexel: 16, width: 32, height: 32,
            frameIndex: 0, family: .redStar, policyFlags: 0b110
        ),
        .init(
            textureID: 0x101, symbol: "gd_texture_red_star_1",
            includePath: "textures/intro_raw/red_star_1.rgba16.inc.c",
            format: .rgba16, bitsPerTexel: 16, width: 32, height: 32,
            frameIndex: 1, family: .redStar, policyFlags: 0b110
        ),
        .init(
            textureID: 0x102, symbol: "gd_texture_red_star_2",
            includePath: "textures/intro_raw/red_star_2.rgba16.inc.c",
            format: .rgba16, bitsPerTexel: 16, width: 32, height: 32,
            frameIndex: 2, family: .redStar, policyFlags: 0b110
        ),
        .init(
            textureID: 0x103, symbol: "gd_texture_red_star_3",
            includePath: "textures/intro_raw/red_star_3.rgba16.inc.c",
            format: .rgba16, bitsPerTexel: 16, width: 32, height: 32,
            frameIndex: 3, family: .redStar, policyFlags: 0b110
        ),
        .init(
            textureID: 0x104, symbol: "gd_texture_red_star_4",
            includePath: "textures/intro_raw/red_star_4.rgba16.inc.c",
            format: .rgba16, bitsPerTexel: 16, width: 32, height: 32,
            frameIndex: 4, family: .redStar, policyFlags: 0b110
        ),
        .init(
            textureID: 0x105, symbol: "gd_texture_red_star_5",
            includePath: "textures/intro_raw/red_star_5.rgba16.inc.c",
            format: .rgba16, bitsPerTexel: 16, width: 32, height: 32,
            frameIndex: 5, family: .redStar, policyFlags: 0b110
        ),
        .init(
            textureID: 0x106, symbol: "gd_texture_red_star_6",
            includePath: "textures/intro_raw/red_star_6.rgba16.inc.c",
            format: .rgba16, bitsPerTexel: 16, width: 32, height: 32,
            frameIndex: 6, family: .redStar, policyFlags: 0b110
        ),
        .init(
            textureID: 0x107, symbol: "gd_texture_red_star_7",
            includePath: "textures/intro_raw/red_star_7.rgba16.inc.c",
            format: .rgba16, bitsPerTexel: 16, width: 32, height: 32,
            frameIndex: 7, family: .redStar, policyFlags: 0b110
        ),
        .init(
            textureID: 0x200, symbol: "gd_texture_white_star_0",
            includePath: "textures/intro_raw/white_star_0.rgba16.inc.c",
            format: .rgba16, bitsPerTexel: 16, width: 32, height: 32,
            frameIndex: 0, family: .whiteStar, policyFlags: 0b110
        ),
        .init(
            textureID: 0x201, symbol: "gd_texture_white_star_1",
            includePath: "textures/intro_raw/white_star_1.rgba16.inc.c",
            format: .rgba16, bitsPerTexel: 16, width: 32, height: 32,
            frameIndex: 1, family: .whiteStar, policyFlags: 0b110
        ),
        .init(
            textureID: 0x202, symbol: "gd_texture_white_star_2",
            includePath: "textures/intro_raw/white_star_2.rgba16.inc.c",
            format: .rgba16, bitsPerTexel: 16, width: 32, height: 32,
            frameIndex: 2, family: .whiteStar, policyFlags: 0b110
        ),
        .init(
            textureID: 0x203, symbol: "gd_texture_white_star_3",
            includePath: "textures/intro_raw/white_star_3.rgba16.inc.c",
            format: .rgba16, bitsPerTexel: 16, width: 32, height: 32,
            frameIndex: 3, family: .whiteStar, policyFlags: 0b110
        ),
        .init(
            textureID: 0x204, symbol: "gd_texture_white_star_4",
            includePath: "textures/intro_raw/white_star_4.rgba16.inc.c",
            format: .rgba16, bitsPerTexel: 16, width: 32, height: 32,
            frameIndex: 4, family: .whiteStar, policyFlags: 0b110
        ),
        .init(
            textureID: 0x205, symbol: "gd_texture_white_star_5",
            includePath: "textures/intro_raw/white_star_5.rgba16.inc.c",
            format: .rgba16, bitsPerTexel: 16, width: 32, height: 32,
            frameIndex: 5, family: .whiteStar, policyFlags: 0b110
        ),
        .init(
            textureID: 0x206, symbol: "gd_texture_white_star_6",
            includePath: "textures/intro_raw/white_star_6.rgba16.inc.c",
            format: .rgba16, bitsPerTexel: 16, width: 32, height: 32,
            frameIndex: 6, family: .whiteStar, policyFlags: 0b110
        ),
        .init(
            textureID: 0x207, symbol: "gd_texture_white_star_7",
            includePath: "textures/intro_raw/white_star_7.rgba16.inc.c",
            format: .rgba16, bitsPerTexel: 16, width: 32, height: 32,
            frameIndex: 7, family: .whiteStar, policyFlags: 0b110
        ),
        .init(
            textureID: 0x300, symbol: "gd_texture_mario_face_shine",
            includePath: "textures/intro_raw/mario_face_shine.ia8.inc.c",
            format: .ia8, bitsPerTexel: 8, width: 32, height: 32,
            frameIndex: 0, family: .faceShine, policyFlags: 0b111
        ),
    ]

    static let routes: [SM64MarioFaceRouteRecord] = [
        .init(
            routeID: .yoshiScene, displayListID: 0,
            viewSymbol: "sYoshiSceneView", objectSymbol: "yoshi_scene",
            updateDomain: .yoshiScene, policyFlags: 0b100,
            textureIDs: Array(0x100...0x107) + Array(0x200...0x207)
        ),
        .init(
            routeID: .yoshiShell, displayListID: 1,
            viewSymbol: "sYoshiSceneGrp", objectSymbol: "yoshi_sh_l1",
            updateDomain: .yoshiScene, policyFlags: 0,
            textureIDs: Array(0x100...0x107) + Array(0x200...0x207)
        ),
        .init(
            routeID: .marioNormal, displayListID: 2,
            viewSymbol: "sMSceneView", objectSymbol: "sMHeadMainDls",
            updateDomain: .marioScene, policyFlags: 0b111,
            textureIDs: [1, 2, 0x300]
        ),
        .init(
            routeID: .marioGameOver, displayListID: 3,
            viewSymbol: "sMSceneView", objectSymbol: "sMHeadMainDls",
            updateDomain: .marioScene, policyFlags: 0b111,
            textureIDs: [1, 2, 0x300]
        ),
        .init(
            routeID: .carScene, displayListID: 4,
            viewSymbol: "sCarSceneView", objectSymbol: "car_scene",
            updateDomain: .carScene, policyFlags: 0b100,
            textureIDs: []
        ),
        .init(
            routeID: .testnet2, displayListID: 5,
            viewSymbol: "sScreenView2", objectSymbol: "testnet2",
            updateDomain: .carScene, policyFlags: 0,
            textureIDs: []
        ),
    ]

    static func route(_ id: SM64MarioFaceGoddardRouteID) -> SM64MarioFaceRouteRecord? {
        routes.first { $0.routeID == id }
    }

    static func texture(_ id: UInt32) -> SM64MarioFaceTextureResource? {
        textures.first { $0.textureID == id }
    }

    static func camera(for route: SM64MarioFaceRouteRecord) -> SM64MarioFaceCameraOrientationRecord {
        SM64MarioFaceCameraOrientationRecord(
            routeID: route.routeID,
            viewSymbol: route.viewSymbol,
            viewportWidth: 320,
            viewportHeight: 240,
            rendererScale100000: 100_000,
            rendererPitchMinDegrees100: -4_500,
            rendererPitchMaxDegrees100: 4_500,
            mainScale100000: 46_799,
            mainPitchMinDegrees100: -3_400,
            mainPitchMaxDegrees100: 3_400,
            cursorX: 160,
            cursorY: 120,
            lightCount: 2,
            lightDirection: [0, 120, 0],
            lightScaleRGB1000: [1000, 0, 0]
        )
    }
}

enum SM64MarioFaceRouteResourceFingerprint {
    static let offset: UInt64 = 1_469_598_103_934_665_603
    static let prime: UInt64 = 1_099_511_628_211

    private static func hash(_ initial: UInt64, _ value: UInt64) -> UInt64 {
        var result = initial
        for byte in 0..<8 {
            result ^= (value >> UInt64(byte * 8)) & 0xFF
            result &*= prime
        }
        return result
    }

    private static func hash(_ initial: UInt64, _ value: UInt32) -> UInt64 {
        hash(initial, UInt64(value))
    }

    private static func hash(_ initial: UInt64, _ value: Int32) -> UInt64 {
        hash(initial, UInt64(bitPattern: Int64(value)))
    }

    private static func hash(_ initial: UInt64, _ values: [UInt32]) -> UInt64 {
        values.reduce(initial) { hash($0, $1) }
    }

    private static func hash(_ initial: UInt64, _ values: [Int32]) -> UInt64 {
        values.reduce(initial) { hash($0, $1) }
    }

    private static func hash(_ initial: UInt64, _ string: String) -> UInt64 {
        var result = hash(initial, UInt64(string.utf8.count))
        for byte in string.utf8 {
            result = hash(result, UInt64(byte))
        }
        return result
    }

    private static func hash(_ initial: UInt64, _ camera: SM64MarioFaceCameraOrientationRecord) -> UInt64 {
        var result = hash(initial, camera.routeID.rawValue)
        result = hash(result, camera.viewSymbol)
        result = hash(result, [
            camera.viewportWidth, camera.viewportHeight, camera.rendererScale100000,
            camera.mainScale100000, camera.cursorX, camera.cursorY, camera.lightCount,
        ])
        result = hash(result, [
            camera.rendererPitchMinDegrees100, camera.rendererPitchMaxDegrees100,
            camera.mainPitchMinDegrees100, camera.mainPitchMaxDegrees100,
        ])
        result = hash(result, camera.lightDirection)
        return hash(result, camera.lightScaleRGB1000)
    }

    static func catalog(
        textures: [SM64MarioFaceTextureResource] = SM64MarioFaceRouteResourceCatalog.textures,
        routes: [SM64MarioFaceRouteRecord] = SM64MarioFaceRouteResourceCatalog.routes
    ) -> UInt64 {
        var result = hash(offset, UInt64(1))
        result = hash(result, UInt64(textures.count))
        for texture in textures {
            result = hash(result, [
                texture.textureID, texture.format.rawValue, texture.bitsPerTexel,
                texture.width, texture.height, texture.frameIndex,
                texture.family.rawValue, texture.policyFlags,
            ])
            result = hash(result, texture.symbol)
            result = hash(result, texture.includePath)
        }
        result = hash(result, UInt64(routes.count))
        for route in routes {
            result = hash(result, [
                route.routeID.rawValue, route.displayListID,
                route.updateDomain.rawValue, route.policyFlags,
                UInt32(route.textureIDs.count),
            ])
            result = hash(result, route.viewSymbol)
            result = hash(result, route.objectSymbol)
            result = hash(result, route.textureIDs)
            result = hash(result, SM64MarioFaceRouteResourceCatalog.camera(for: route))
        }
        return result
    }
}

struct SM64MarioFaceRouteRenderPacket: Equatable, Sendable {
    let route: SM64MarioFaceRouteRecord
    let camera: SM64MarioFaceCameraOrientationRecord
    let textures: [SM64MarioFaceTextureResource]
    let face: SM64MarioFaceRenderFramePacket
    let resourceFingerprint: UInt64
    let fingerprint: UInt64
}

enum SM64MarioFaceRouteRenderPacketBuilder {
    static func make(
        routeID: SM64MarioFaceGoddardRouteID,
        face: SM64MarioFaceRenderFramePacket
    ) -> SM64MarioFaceRouteRenderPacket? {
        guard let route = SM64MarioFaceRouteResourceCatalog.route(routeID) else { return nil }
        let camera = SM64MarioFaceRouteResourceCatalog.camera(for: route)
        let textures = route.textureIDs.compactMap(SM64MarioFaceRouteResourceCatalog.texture)
        guard textures.count == route.textureIDs.count else { return nil }
        let resourceFingerprint = SM64MarioFaceRouteResourceFingerprint.catalog()
        var fingerprint = SM64MarioFaceRouteResourceFingerprint.offset
        fingerprint = hash(fingerprint, resourceFingerprint)
        fingerprint = hash(fingerprint, route.routeID.rawValue)
        fingerprint = hash(fingerprint, camera.viewportWidth)
        fingerprint = hash(fingerprint, camera.viewportHeight)
        fingerprint = hash(fingerprint, SM64MarioFaceRenderPacketFingerprint.packet(face))
        fingerprint = hash(fingerprint, UInt64(textures.count))
        for texture in textures { fingerprint = hash(fingerprint, texture.textureID) }
        return SM64MarioFaceRouteRenderPacket(
            route: route, camera: camera, textures: textures, face: face,
            resourceFingerprint: resourceFingerprint, fingerprint: fingerprint
        )
    }

    private static func hash(_ initial: UInt64, _ value: UInt64) -> UInt64 {
        var result = initial
        for byte in 0..<8 {
            result ^= (value >> UInt64(byte * 8)) & 0xFF
            result &*= SM64MarioFaceRouteResourceFingerprint.prime
        }
        return result
    }

    private static func hash(_ initial: UInt64, _ value: UInt32) -> UInt64 {
        hash(initial, UInt64(value))
    }
}

/// Schema-4 render-domain records for the route/resource packet.  The first
/// records are entirely source metadata and can be compared before a Metal
/// encoder is involved; the final record carries the already-qualified M30l
/// face-packet fingerprint.
enum SM64MarioFaceRouteRenderOracle {
    static let domain: UInt32 = SM64RenderOracleTraceAdapter.domain
    static let recordKind: UInt32 = SM64RenderOracleTraceAdapter.recordKind
    /// C's `sm64_modern_parity_record_mario_face_route` uses the render
    /// inventory event ID below. Its values deliberately stay at the copied
    /// route/camera boundary; texture/resource fingerprints remain separate
    /// records so this hook never receives a pointer or a Metal handle.
    static let liveCEventID: UInt64 = 5
    static let routeRecordBase: UInt64 = 0x4D46_5200
    static let cameraRecordBase: UInt64 = 0x4D46_5300
    static let textureRecordBase: UInt64 = 0x4D46_5400
    static let faceRecordBase: UInt64 = 0x4D46_5500

    static func metadataRecords(
        route: SM64MarioFaceRouteRecord,
        camera: SM64MarioFaceCameraOrientationRecord,
        textures: [SM64MarioFaceTextureResource],
        simulationTick: UInt64,
        sequenceStart: UInt32
    ) throws -> [SM64OracleTraceRecord] {
        var sequence = sequenceStart
        var records = [
            try SM64OracleTraceRecord(
                simulationTick: simulationTick, domain: domain,
                recordKind: recordKind, subjectID: UInt64(route.routeID.rawValue),
                recordID: routeRecordBase | UInt64(route.routeID.rawValue),
                sequence: sequence,
                values: [
                    UInt64(route.routeID.rawValue), UInt64(route.displayListID),
                    UInt64(route.updateDomain.rawValue), UInt64(route.policyFlags),
                    UInt64(textures.count), UInt64(camera.viewportWidth),
                    UInt64(camera.viewportHeight),
                    SM64MarioFaceRouteResourceFingerprint.catalog(),
                ]
            )
        ]
        sequence &+= 1
        records.append(try SM64OracleTraceRecord(
            simulationTick: simulationTick, domain: domain,
            recordKind: recordKind, subjectID: UInt64(route.routeID.rawValue),
            recordID: cameraRecordBase | UInt64(route.routeID.rawValue),
            sequence: sequence,
            values: [
                UInt64(camera.viewportWidth), UInt64(camera.viewportHeight),
                UInt64(camera.rendererScale100000),
                UInt64(bitPattern: Int64(camera.rendererPitchMinDegrees100)),
                UInt64(bitPattern: Int64(camera.rendererPitchMaxDegrees100)),
                UInt64(camera.mainScale100000),
                UInt64(bitPattern: Int64(camera.mainPitchMinDegrees100)),
                UInt64(bitPattern: Int64(camera.mainPitchMaxDegrees100)),
            ]
        ))
        sequence &+= 1
        for texture in textures {
            records.append(try SM64OracleTraceRecord(
                simulationTick: simulationTick, domain: domain,
                recordKind: recordKind, subjectID: UInt64(route.routeID.rawValue),
                recordID: textureRecordBase | UInt64(texture.textureID),
                sequence: sequence,
                values: [
                    UInt64(texture.textureID), UInt64(texture.format.rawValue),
                    UInt64(texture.bitsPerTexel), UInt64(texture.width),
                    UInt64(texture.height), UInt64(texture.frameIndex),
                    UInt64(texture.family.rawValue), UInt64(texture.policyFlags),
                ]
            ))
            sequence &+= 1
        }
        return records
    }

    static func records(
        packet: SM64MarioFaceRouteRenderPacket,
        simulationTick: UInt64,
        sequenceStart: UInt32 = 0
    ) throws -> [SM64OracleTraceRecord] {
        var records = try metadataRecords(
            route: packet.route, camera: packet.camera, textures: packet.textures,
            simulationTick: simulationTick, sequenceStart: sequenceStart
        )
        records.append(try SM64OracleTraceRecord(
            simulationTick: simulationTick, domain: domain,
            recordKind: recordKind, subjectID: UInt64(packet.route.routeID.rawValue),
            recordID: faceRecordBase | UInt64(packet.route.routeID.rawValue),
            sequence: records.last.map { $0.sequence &+ 1 } ?? sequenceStart,
            values: [
                SM64MarioFaceRenderPacketFingerprint.packet(packet.face),
                packet.fingerprint, packet.resourceFingerprint,
                UInt64(packet.face.animationBank), UInt64(packet.face.animationFrameQ16),
                UInt64(packet.face.residentChannelCount),
                UInt64(packet.face.unavailableChannelCount),
                packet.face.channelMask,
            ]
        ))
        return records
    }

    static func liveCRecord(
        route: SM64MarioFaceRouteRecord,
        simulationTick: UInt64,
        sequence: UInt32
    ) throws -> SM64OracleTraceRecord {
        try SM64OracleTraceRecord(
            simulationTick: simulationTick,
            domain: domain,
            recordKind: recordKind,
            subjectID: 0,
            recordID: liveCEventID,
            sequence: sequence,
            values: [
                UInt64(route.routeID.rawValue), UInt64(route.displayListID),
                UInt64(route.updateDomain.rawValue), UInt64(route.policyFlags),
                320, 240, 2,
            ]
        )
    }

    static func fingerprint(_ records: [SM64OracleTraceRecord]) -> UInt64 {
        var result = SM64OracleTraceHash.offset
        result = update(result, UInt64(records.count))
        for record in records { result = update(result, record.canonicalHash) }
        return result
    }

    private static func update(_ initial: UInt64, _ value: UInt64) -> UInt64 {
        var result = initial
        for byte in 0..<8 {
            result ^= (value >> UInt64(byte * 8)) & 0xFF
            result &*= SM64OracleTraceHash.prime
        }
        return result
    }
}
