import Foundation
struct SM64MovingCoinObjectEffectRecord: Equatable, Sendable { let objectID: SM64ObjectID; let output: SM64MovingCoinOutput; let spawnedSparkles: SM64ObjectID? }
final class SM64MovingCoinObjectBridge {
    static let movingYellowCoinBehaviorIdentity: UInt64 = 0x6268_765F_6D7963
    static let movingBlueCoinBehaviorIdentity: UInt64 = 0x6268_765F_6D6263
    static let blueCoinSlidingBehaviorIdentity: UInt64 = 0x6268_765F_6263736C
    static let blueCoinJumpingBehaviorIdentity: UInt64 = 0x6268_765F_626A7031
    private struct State { let kind: SM64MovingCoinKind; var grounded:Bool; var noY:Bool; var floorDeath:Bool; var within:Bool; var interacted:Bool }
    private let goldenCoinSparklesBridge: SM64GoldenCoinSparklesObjectBridge?
    private var states:[SM64ObjectID:State]=[:]; private(set) var effectLog:[SM64MovingCoinObjectEffectRecord]=[]
    private var inputAngles: [SM64ObjectID: Int32] = [:]
    private var wallHits: [SM64ObjectID: Bool] = [:]
    private var within500: [SM64ObjectID: Bool] = [:]
    private var within1000: [SM64ObjectID: Bool] = [:]
    init(goldenCoinSparklesBridge:SM64GoldenCoinSparklesObjectBridge?=nil){self.goldenCoinSparklesBridge=goldenCoinSparklesBridge}
    var registeredIDs:[SM64ObjectID]{states.keys.sorted{$0.slot == $1.slot ? $0.generation < $1.generation : $0.slot < $1.slot}}
    func beginExternalTick(){effectLog.removeAll(keepingCapacity:true)}
    @discardableResult func spawnCoin(in engineState: SM64SwiftEngineState,kind:SM64MovingCoinKind = .yellow,position:SM64ObjectVector3 = .zero)throws->SM64ObjectID{let behavior:UInt64;switch kind{case .yellow:behavior=Self.movingYellowCoinBehaviorIdentity;case .blue:behavior=Self.movingBlueCoinBehaviorIdentity;case .blueSliding:behavior=Self.blueCoinSlidingBehaviorIdentity;case .blueJumping:behavior=Self.blueCoinJumpingBehaviorIdentity};let list:SM64ObjectList=kind.isSlidingOrJumping ? .generalActor : .level;let id=try engineState.spawnObject(in:list,behaviorIdentity:behavior);guard attach(id,kind:kind,position:position,in:engineState.objects)else{_ = engineState.objects.despawn(id);preconditionFailure("newly spawned moving coin could not attach")};return id}
    @discardableResult func attach(_ id:SM64ObjectID,kind:SM64MovingCoinKind,position:SM64ObjectVector3,in pool:SM64ObjectPool)->Bool{guard pool.record(for:id) != nil else{return false};states[id]=State(kind:kind,grounded:false,noY:false,floorDeath:false,within:false,interacted:false);return pool.mutate(id){r in r.position=position;r.homePosition=position;r.interactionType=1<<4;r.damageOrCoinValue=kind.isBlue ? 5:1;r.hitboxRadius=100;r.hitboxHeight=64;r.gravity=kind.isSlidingOrJumping ? 3:(kind == .blue ? 5:3);r.friction=kind.isSlidingOrJumping ? 0.98:1;r.buoyancy=1.5;r.intangibleTimer=kind == .blueJumping ? 1:0;r.objectFlags |= SM64ObjectScheduler.objectFlagUpdateGfxPositionAndAngle|SM64ObjectScheduler.objectFlagBuildTransform}}
    @discardableResult func setInputs(grounded:Bool,noYVelocity:Bool=false,floorDeath:Bool=false,withinMarioRadius:Bool=false,interacted:Bool=false,angleToMario:Int32=0,collisionWall:Bool=false,withinMario500:Bool=false,withinMario1000:Bool=false,for id:SM64ObjectID)->Bool{guard var s=states[id]else{return false};s.grounded=grounded;s.noY=noYVelocity;s.floorDeath=floorDeath;s.within=withinMarioRadius;s.interacted=interacted;states[id]=s;inputAngles[id]=angleToMario;wallHits[id]=collisionWall;within500[id]=withinMario500;within1000[id]=withinMario1000;return true}
    @discardableResult func updateInline(_ id:SM64ObjectID,state engineState:SM64SwiftEngineState)->Bool{guard var s=states[id],let r=engineState.objects.record(for:id)else{return false};let o=SM64MovingCoinBehavior.update(.init(kind:s.kind,action:r.action,timer:r.timer,forwardVelocity:r.forwardVelocity,velocityY:r.velocity.y,collisionGrounded:s.grounded,collisionNoYVelocity:s.noY,floorDeath:s.floorDeath,withinMarioRadius:s.within,interacted:s.interacted,angleToMario:inputAngles[id] ?? r.angleToMario,collisionWall:wallHits[id] ?? false,withinMario500:within500[id] ?? false,withinMario1000:within1000[id] ?? false));s.grounded=false;s.noY=false;s.floorDeath=false;s.within=false;s.interacted=false;states[id]=s;inputAngles.removeValue(forKey:id);wallHits.removeValue(forKey:id);within500.removeValue(forKey:id);within1000.removeValue(forKey:id);var spark:SM64ObjectID?;if o.spawnGoldenSparkles,let golden=goldenCoinSparklesBridge{spark=try? golden.spawnSparkles(in:engineState,position:r.position)};_ = engineState.objects.mutate(id){n in n.action=o.action;n.timer=o.timer;n.forwardVelocity=o.forwardVelocity;n.velocity.y=o.velocityY;n.moveAngles.yaw=o.moveYaw;n.intangibleTimer=o.tangible ? -1:1;n.graphFlags=o.visible ? n.graphFlags & ~UInt16(0x10):n.graphFlags | UInt16(0x10);n.interactionStatus=0;if o.shouldDelete{n.activeFlags=0};n.objectFlags |= SM64ObjectScheduler.objectFlagUpdateGfxPositionAndAngle|SM64ObjectScheduler.objectFlagBuildTransform};effectLog.append(.init(objectID:id,output:o,spawnedSparkles:spark));return true}
    func remove(_ id:SM64ObjectID){states.removeValue(forKey:id);inputAngles.removeValue(forKey:id);wallHits.removeValue(forKey:id);within500.removeValue(forKey:id);within1000.removeValue(forKey:id)};func pruneExternal(unloaded:[SM64ObjectID],pool:SM64ObjectPool){for id in unloaded{remove(id)};for id in registeredIDs where pool.record(for:id)==nil{remove(id)}}
}
