import Foundation
struct SM64WaterPillarObjectEffectRecord:Equatable,Sendable{let objectID:SM64ObjectID;let output:SM64WaterPillarOutput;let peerID:SM64ObjectID?}
final class SM64WaterPillarObjectBridge{
 static let defaultBehaviorIdentity:UInt64=0x6268_765F_77706C
 private struct State{var drained:Bool;var groundPounded:Bool;var peerAction:Int32?}
 private var states:[SM64ObjectID:State]=[:];private(set)var effectLog:[SM64WaterPillarObjectEffectRecord]=[];private(set)var environmentLevel0:Int32=0;private(set)var environmentLevel2:Int32=0
 var registeredIDs:[SM64ObjectID]{states.keys.sorted{$0.slot == $1.slot ? $0.generation < $1.generation : $0.slot < $1.slot}}
 func beginExternalTick(){effectLog.removeAll(keepingCapacity:true)}
 @discardableResult func spawnPillar(in e:SM64SwiftEngineState,position:SM64ObjectVector3 = .zero,drained:Bool = false,environmentLevel:Int32 = 0)throws->SM64ObjectID{environmentLevel0=environmentLevel;environmentLevel2=environmentLevel;let id=try e.spawnObject(in:.surface,behaviorIdentity:Self.defaultBehaviorIdentity);guard attach(id,position:position,drained:drained,in:e.objects)else{_ = e.objects.despawn(id);preconditionFailure("newly spawned water pillar could not attach")};return id}
 @discardableResult func attach(_ id:SM64ObjectID,position:SM64ObjectVector3,drained:Bool,in p:SM64ObjectPool)->Bool{guard p.record(for:id) != nil else{return false};states[id]=State(drained:drained,groundPounded:false,peerAction:nil);return p.mutate(id){r in r.position=position;r.homePosition=position;r.action=drained ? 5:0;r.collisionDistance=4000;r.objectFlags |= SM64ObjectScheduler.objectFlagUpdateGfxPositionAndAngle|SM64ObjectScheduler.objectFlagBuildTransform}}
 @discardableResult func setGroundPounded(_ v:Bool,for id:SM64ObjectID)->Bool{guard var s=states[id]else{return false};s.groundPounded=v;states[id]=s;return true}
 @discardableResult func setPeerAction(_ a:Int32?,for id:SM64ObjectID)->Bool{guard var s=states[id]else{return false};s.peerAction=a;states[id]=s;return true}
 @discardableResult func updateInline(_ id:SM64ObjectID,state e:SM64SwiftEngineState)->Bool{guard var s=states[id],let r=e.objects.record(for:id)else{return false};let peer=nearestPeer(excluding:id,to:r.position,in:e.objects);let pAction=s.peerAction ?? peer.flatMap{$0}.flatMap{e.objects.record(for:$0)?.action};let o=SM64WaterPillarBehavior.update(.init(action:SM64WaterPillarAction(rawValue:r.action) ?? .waiting,timer:r.timer,positionY:r.position.y,groundPounded:s.groundPounded,peerAction:pAction,drained:s.drained,environmentLevel0:environmentLevel0,environmentLevel2:environmentLevel2));s.groundPounded=false;if o.setMoatDrained{s.drained=true};states[id]=s;environmentLevel0=o.environmentLevel0;environmentLevel2=o.environmentLevel2;_ = e.objects.mutate(id){n in n.action=o.action.rawValue;n.timer=o.timer;n.position.y=o.positionY};effectLog.append(.init(objectID:id,output:o,peerID:peer));return true}
 private func nearestPeer(excluding id:SM64ObjectID,to p:SM64ObjectVector3,in pool:SM64ObjectPool)->SM64ObjectID?{var best:(Float,SM64ObjectID)?;for c in states.keys where c != id{guard let r=pool.record(for:c)else{continue};let dx=r.position.x-p.x;let dy=r.position.y-p.y;let dz=r.position.z-p.z;let d=dx*dx+dy*dy+dz*dz;if best == nil || d < best!.0{best=(d,c)}};return best?.1}
 func remove(_ id:SM64ObjectID){states.removeValue(forKey:id)};func pruneExternal(unloaded:[SM64ObjectID],pool:SM64ObjectPool){for id in unloaded{remove(id)};for id in registeredIDs where pool.record(for:id)==nil{remove(id)}}
}
